#!/usr/bin/env python3
"""Black-box Tigramite PCMCI multi-variable conformance fixture (val/p matrices + FDR).

Usage:
    uv run --python 3.12 --with numpy --with 'tigramite==5.2.1.30' \\
      python scripts/conformance/generate_tigramite_pcmci_multivar.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "conformance" / "tigramite" / "pcmci_multivar"

N = 600
ALPHA = 0.05
MAX_LAG = 2
VAR_NAMES = ["a", "b", "c", "d"]
SEED = 3
FDR = True


def synthesize() -> np.ndarray:
    """4-var VAR with lagged + light noise; strong a→b lag1, b→c lag1, a→d lag2."""
    rng = np.random.default_rng(SEED)
    data = np.zeros((N, 4))
    eps = rng.normal(size=(N, 4)) * 0.25
    data[0] = eps[0]
    for t in range(1, N):
        a_prev = data[t - 1, 0]
        b_prev = data[t - 1, 1]
        a_lag2 = data[t - 2, 0] if t >= 2 else 0.0
        data[t, 0] = 0.2 * a_prev + eps[t, 0]
        data[t, 1] = 0.7 * a_prev + 0.15 * b_prev + eps[t, 1]
        data[t, 2] = 0.65 * b_prev + eps[t, 2]
        data[t, 3] = 0.55 * a_lag2 + eps[t, 3]
    return data


def parents_from_tigramite(results, pcmci, var_names: list[str]) -> list[dict]:
    parents_dict = pcmci.return_parents_dict(
        graph=results["graph"], val_matrix=results["val_matrix"]
    )
    out: list[dict] = []
    for target_i, parents in parents_dict.items():
        for source_i, lag in parents:
            source_lag = abs(int(lag))
            if source_lag == 0:
                continue
            out.append(
                {
                    "source": var_names[int(source_i)],
                    "source_lag": source_lag,
                    "target": var_names[int(target_i)],
                    "target_lag": 0,
                }
            )
    return out


def matrix_to_list(mat) -> list:
    return np.asarray(mat, dtype=float).tolist()


def try_tigramite(data: np.ndarray) -> dict:
    try:
        import tigramite  # type: ignore
        from tigramite import data_processing as pp  # type: ignore
        from tigramite.independence_tests.parcorr import ParCorr  # type: ignore
        from tigramite.pcmci import PCMCI  # type: ignore
    except ImportError:
        return {"available": False, "note": "Tigramite not installed"}

    dataframe = pp.DataFrame(data, var_names=VAR_NAMES)
    pcmci = PCMCI(dataframe=dataframe, cond_ind_test=ParCorr())
    results = pcmci.run_pcmci(tau_max=MAX_LAG, pc_alpha=ALPHA, fdr_method="fdr_bh" if FDR else "none")
    recovered = parents_from_tigramite(results, pcmci, VAR_NAMES)
    version = getattr(tigramite, "__version__", None) or "5.2.1.30"
    out = {
        "available": True,
        "tigramite_version": version,
        "note": "black-box execution only; no source translation",
        "graph_shape": list(np.asarray(results["graph"]).shape),
        "recovered_parents": recovered,
        "val_matrix": matrix_to_list(results["val_matrix"]),
        "p_matrix": matrix_to_list(results["p_matrix"]),
        "alpha": ALPHA,
        "max_lag": MAX_LAG,
        "fdr": FDR,
        "pin_note": "PyPI 5.2.1.30 (same 5.2.1 line as parity pin)",
    }
    if "q_matrix" in results and results["q_matrix"] is not None:
        out["q_matrix"] = matrix_to_list(results["q_matrix"])
    return out


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    data = synthesize()
    with (OUT / "data.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=VAR_NAMES)
        w.writeheader()
        for row in data:
            w.writerow({n: float(v) for n, v in zip(VAR_NAMES, row, strict=True)})

    tig = try_tigramite(data)
    true_parents = [
        {"source": "a", "source_lag": 1, "target": "b", "target_lag": 0},
        {"source": "b", "source_lag": 1, "target": "c", "target_lag": 0},
        {"source": "a", "source_lag": 2, "target": "d", "target_lag": 0},
    ]
    expected = {
        "true_parents": true_parents,
        "tolerance_class": "StableFloat",
        "atol_stat": 0.05,
        "rtol_stat": 0.15,
        "atol_p": 0.05,
        "rtol_p": 0.25,
        "max_lag": MAX_LAG,
        "alpha": ALPHA,
        "fdr": FDR,
        "n": N,
        "variables": VAR_NAMES,
        "scm": "4-var VAR; a→b@1, b→c@1, a→d@2; seed=3",
        "tigramite": tig,
        "generation": {
            "script": "scripts/conformance/generate_tigramite_pcmci_multivar.py",
            "baseline_pin": "parity/tigramite.toml",
            "env": "uv run --python 3.12 --with numpy --with tigramite==5.2.1.30",
        },
    }
    (OUT / "expected.json").write_text(json.dumps(expected, indent=2) + "\n")
    (OUT / "README.md").write_text(
        "# Tigramite PCMCI multi-var conformance\n\n"
        "# Generated by scripts/conformance/generate_tigramite_pcmci_multivar.py\n\n"
        "≥4 variables; compares edge sets and val/p/(q) matrix entries.\n"
    )
    print(f"wrote {OUT}")
    print("available", tig.get("available"), "parents", tig.get("recovered_parents"))


if __name__ == "__main__":
    main()
