//! Generated from `parity/support_*.toml`. Do not edit.

#![allow(missing_docs)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Copy, Debug)]
pub struct NaRule {
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct AllowedRule {
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
    pub parent: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct LicensedCell {
    pub query: &'static str,
    pub graph_class: &'static str,
    pub structure: &'static str,
    pub inference: &'static str,
    pub validation: &'static str,
}

pub static NA_RULES: &[NaRule] = &[
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect", "TemporalMediationEffect"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag", "CoDetermined", "Unknown"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Temporal contrast queries require a temporal graph class.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "AverageDerivative", "AverageEffect", "ChangeAttribution", "ConditionalEffect", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "MediationEffect", "PathSpecificEffect", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Static queries are not a temporal-graph cell; use PulseEffect, SustainedEffect, or a temporal ResponseCurve/InterventionResponse attachment.",
    },
    NaRule {
        queries: Some(&["TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "TransportQuery and InterferenceQuery are typed against static graphs; they do not denote on a temporal graph class.",
    },
    NaRule {
        queries: Some(&["ResponseCurve"]),
        graph_classes: Some(&["Dag", "TemporalDag", "Cpdag", "Pag", "TemporalCpdag", "TemporalPag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "cheap and full denote the ATE-shaped scalar refuter suite; a function-valued curve has no such state.",
    },
    NaRule {
        queries: Some(&["ResponseCurve"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "cheap and full denote the ATE-shaped scalar refuter suite; a graph-posterior response remains function-valued or atom-mixed with no licensed scalar-refuter state.",
    },
    NaRule {
        queries: Some(&["InterventionResponse"]),
        graph_classes: Some(&["TemporalDag", "Cpdag", "Pag", "TemporalCpdag", "TemporalPag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "cheap and full denote the ATE-shaped scalar refuter suite; temporal and class-aware InterventionResponse remain function-valued or envelope-mixed surfaces with no licensed scalar-refuter state.",
    },
    NaRule {
        queries: Some(&["InterventionResponse"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted", "graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: Some(&["cheap", "full"]),
        reason: "Bayesian InterventionResponse has no licensed scalar-refuter state; cheap/full name the Frequentist ATE-shaped suite.",
    },
    NaRule {
        queries: Some(&["PointDerivative", "Elasticity", "SemiElasticity", "AverageDerivative", "DirectionalDerivative", "ResponseJacobian"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Derivative-native validation is not implemented; ATE refuters do not apply.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "AverageDerivative", "ChangeAttribution", "ConditionalEffect", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "InterventionResponse", "MediationEffect", "PathSpecificEffect", "PointDerivative", "ResponseCurve", "ResponseJacobian", "SemiElasticity", "TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["Unknown"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Unknown-tier cells license the two-scenario AverageEffect envelope only.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "AverageDerivative", "ChangeAttribution", "ConditionalEffect", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "MediationEffect", "PathSpecificEffect", "PointDerivative", "ResponseCurve", "ResponseJacobian", "SemiElasticity", "TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["CoDetermined"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "CoDetermined cells license AverageEffect and joint InterventionResponse only.",
    },
    NaRule {
        queries: None,
        graph_classes: Some(&["CoDetermined", "Unknown"]),
        structures: Some(&["accepted", "graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Tier-rule backgrounds are an explicit structure source.",
    },
    NaRule {
        queries: None,
        graph_classes: Some(&["CoDetermined", "Unknown"]),
        structures: None,
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Tier-rule cells are Frequentist (cell.aipw joint / two-scenario envelope).",
    },
    NaRule {
        queries: Some(&["AverageEffect", "InterventionResponse"]),
        graph_classes: Some(&["CoDetermined", "Unknown"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "cheap and full name the ATE-shaped scalar refuter suite; CoDetermined joint IR and the Unknown envelope have no licensed scalar-refuter state.",
    }
];

pub static CLOSED_RULES: &[NaRule] = &[
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Counterfactual requires a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Derivatives require a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["Admg"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Admg response has no functional plug-in; licensed general-ID ATE does not estimate a curve.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "graph-posterior structures are refused: a path, distribution, or mediation mixture is not a single estimand across posterior atoms.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: Some(&["accepted"]),
        inferences: None,
        validations: None,
        reason: "Accepted path queries require a Dag.",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Cpdag", "Pag"]),
        structures: Some(&["accepted"]),
        inferences: None,
        validations: None,
        reason: "Accepted InterventionalDistribution is licensed on Dag and Admg; Cpdag/Pag remain refused.",
    },
    NaRule {
        queries: Some(&["MediationEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "MediationEffect requires a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "ChangeAttribution"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "AnomalyAttribution and ChangeAttribution require a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "ChangeAttribution"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["accepted", "graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Attribution is licensed only for an explicit Dag at validation none.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "ChangeAttribution"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Attribution has no Bayesian draw path; the licensed cells are Frequentist.",
    },
    NaRule {
        queries: Some(&["AnomalyAttribution", "ChangeAttribution"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Attribution has no native refuter suite; ATE refuters do not apply.",
    },
    NaRule {
        queries: Some(&["TransportQuery"]),
        graph_classes: Some(&["Dag", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Licensed TransportQuery is Admg-only; selection diagrams are ADMGs. Recursive sID outside the implemented subset is NotCertified.",
    },
    NaRule {
        queries: Some(&["TransportQuery"]),
        graph_classes: Some(&["Admg"]),
        structures: Some(&["accepted"]),
        inferences: None,
        validations: None,
        reason: "TransportQuery is licensed only for an explicit Admg at validation none.",
    },
    NaRule {
        queries: Some(&["TransportQuery"]),
        graph_classes: Some(&["Admg"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "TransportQuery graph-posterior mixtures are not staged.",
    },
    NaRule {
        queries: Some(&["TransportQuery"]),
        graph_classes: Some(&["Admg"]),
        structures: None,
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "TransportQuery has no Bayesian trial-to-target estimator.",
    },
    NaRule {
        queries: Some(&["TransportQuery"]),
        graph_classes: Some(&["Admg"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "TransportQuery has no native refuter suite; ATE refuters do not apply.",
    },
    NaRule {
        queries: Some(&["InterferenceQuery"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Licensed InterferenceQuery is Dag-only; the graph binds schema/outcome, it does not identify the contrast.",
    },
    NaRule {
        queries: Some(&["InterferenceQuery"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["accepted"]),
        inferences: None,
        validations: None,
        reason: "InterferenceQuery is licensed only for an explicit Dag at validation none.",
    },
    NaRule {
        queries: Some(&["InterferenceQuery"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "InterferenceQuery graph-posterior mixtures are not staged.",
    },
    NaRule {
        queries: Some(&["InterferenceQuery"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "InterferenceQuery is design-based Frequentist; there is no Bayesian randomization estimator.",
    },
    NaRule {
        queries: Some(&["InterferenceQuery"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "InterferenceQuery has no native refuter suite; ATE refuters do not apply.",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Admg"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "ConditionalEffect on Admg has no compile arm; Dag, Cpdag, and Pag are licensed.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Admg", "Pag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path-specific queries execute only on a supplied static Dag; a directly supplied Admg/Pag hits the same static-Dag requirement (accepted/graph-posterior Admg and Pag are already refused above).",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Pag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries execute only on a supplied static Dag or Admg; a directly supplied Pag hits the static-Dag/Admg requirement.",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Admg"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "ADMG InterventionalDistribution is licensed at validation none; cheap/full remain Dag-only.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Latent-confounded TemporalPag natural mediation is outside the existing cross-world identification theory; DAG-completion engineering cannot license it.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalCpdag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_dbn_posterior_bayesian is TemporalDag-shaped; TemporalCpdag posterior atoms are not mixed into a mediation envelope.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "MediationEffect", "PathSpecificEffect", "PointDerivative", "ResponseJacobian", "SemiElasticity", "TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist graph-posterior mixing on DAG atoms is licensed for AverageEffect, ConditionalEffect, and static ResponseCurve/one-coordinate InterventionResponse. The listed static families remain unsupported.",
    },
    NaRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist graph-posterior mixing is licensed only for DAG atoms. ADMG/CPDAG/PAG posterior atoms remain refused.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist DBN-posterior Pulse/Sustained effects and single-horizon TemporalMediationEffect are licensed. Temporal response mixtures still require their query-specific composite evaluators.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist DBN-posterior mediation is licensed for TemporalDag atoms. TemporalCpdag/TemporalPag posterior atoms need a class-aware combiner that retains unidentified class mass.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: Some(&["cheap", "full"]),
        reason: "Frequentist DBN-posterior TemporalMediationEffect is licensed at validation none. Mediation refuters are not run per atom against that atom's own contrast and mixed by graph weight on this path (the Bayesian DBN mediation cells do this), so cheap/full stay refused.",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "ConditionalEffect graph-posterior mixing is licensed only for DAG atoms. Cpdag/Pag posterior atoms remain refused.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag", "TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Graph-posterior response currently executes only static DAG atoms; ADMG/CPDAG/PAG and temporal posterior atoms require their class-specific evaluators.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Cpdag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path-specific queries execute only on a supplied static Dag and distribution queries only on a supplied static Dag or Admg; a directly supplied Cpdag hits that requirement (Admg/Pag explicit already named above).",
    },
    NaRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_graph_posterior_bayesian is Dag-shaped; Admg/Cpdag/Pag posterior atoms are not mixed into an ATE envelope.",
    },
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_dbn_posterior_bayesian is TemporalDag-shaped; TemporalCpdag/TemporalPag posterior atoms are not mixed into a temporal envelope.",
    },
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist DBN-posterior Pulse/Sustained mixing is licensed for TemporalDag atoms. TemporalCpdag/TemporalPag posterior atoms need a class-aware combiner that retains unidentified class mass; completion enumeration is not posterior probability.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Cpdag", "Admg", "Pag"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Query-native functional validation requires a Dag.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Graph-posterior derivative mixtures are not staged; the licensed derivative cells are Frequentist or Bayesian explicit or accepted Dag at validation none.",
    },
    NaRule {
        queries: Some(&["MediationEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Graph-posterior mediation mixtures are not staged; the licensed MediationEffect cells are Frequentist or Bayesian explicit or accepted Dag.",
    },
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Staged counterfactuals require a supplied Dag; graph-posterior structures are refused.",
    },
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Counterfactual cheap/full are not licensed; there is no native ITE refuter suite and ATE refuters do not apply.",
    }
];

pub static ALLOWED_RULES: &[AllowedRule] = &[

];

pub static LICENSED: &[LicensedCell] = &[
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PointDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PointDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "Elasticity",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "Elasticity",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SemiElasticity",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SemiElasticity",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "DirectionalDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "DirectionalDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseJacobian",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseJacobian",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "Counterfactual",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "Counterfactual",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "CoDetermined",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "CoDetermined",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Unknown",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "Counterfactual",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "Counterfactual",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "DirectionalDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "DirectionalDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "Elasticity",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "Elasticity",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PointDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PointDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseJacobian",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseJacobian",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SemiElasticity",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SemiElasticity",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AnomalyAttribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ChangeAttribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TransportQuery",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterferenceQuery",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    }
];
