//! Generated from `parity/support_*.toml`. Do not edit.

#![allow(missing_docs)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Copy, Debug)]
pub struct NaRule {
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct AllowedRule {
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
    pub parent: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct LicensedCell {
    pub query: &'static str,
    pub graph_class: &'static str,
    pub structure: &'static str,
    pub inference: &'static str,
    pub validation: &'static str,
}

pub static NA_RULES: &[NaRule] = &[
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect", "TemporalMediationEffect"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Temporal contrast queries require a temporal graph class.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "AverageEffect", "ConditionalEffect", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "MediationEffect", "PathSpecificEffect", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Static queries are not a temporal-graph cell; use PulseEffect, SustainedEffect, or a temporal ResponseCurve/InterventionResponse attachment.",
    },
    NaRule {
        queries: Some(&["TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "TransportQuery and InterferenceQuery are typed against static graphs; they do not denote on a temporal graph class.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["Dag", "TemporalDag", "Cpdag", "Pag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "cheap and full denote the ATE-shaped scalar refuter suite; a function-valued estimand has no such state.",
    },
    NaRule {
        queries: Some(&["PointDerivative", "Elasticity", "SemiElasticity", "AverageDerivative", "DirectionalDerivative", "ResponseJacobian"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Derivative-native validation is not implemented; ATE refuters do not apply.",
    }
];

pub static CLOSED_RULES: &[NaRule] = &[
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Counterfactual requires a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Derivatives require a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["Admg"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Admg response has no functional plug-in; licensed general-ID ATE does not estimate a curve.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Graph-posterior path and distribution mixtures are not staged.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: Some(&["accepted"]),
        inferences: None,
        validations: None,
        reason: "Accepted path and distribution queries require a Dag.",
    },
    NaRule {
        queries: Some(&["MediationEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "MediationEffect requires a supplied static Dag.",
    },
    NaRule {
        queries: Some(&["TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Stage transport and interference APIs are not licensed analyze cells; sID outside the implemented subset is NotCertified.",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Admg"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "ConditionalEffect on Admg has no compile arm; Dag, Cpdag, and Pag are licensed.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Admg", "Pag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries execute only on a supplied static Dag; a directly supplied Admg/Pag hits the same static-Dag requirement (accepted/graph-posterior Admg and Pag are already refused above).",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Admg", "Pag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries execute only on a supplied static Dag; a directly supplied Admg/Pag hits the same static-Dag requirement (accepted/graph-posterior Admg and Pag are already refused above).",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "TemporalMediationEffect compiles only against a supplied TemporalDag; compile.rs has no Mediation arm for TemporalCpdag/TemporalPag.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "ConditionalEffect", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "InterventionResponse", "MediationEffect", "PathSpecificEffect", "PointDerivative", "ResponseCurve", "ResponseJacobian", "SemiElasticity", "TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist graph-posterior mixing is licensed only for AverageEffect on DAG atoms. Other static query families are unsupported for this structure/inference coordinate.",
    },
    NaRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist graph-posterior mixing is licensed only for DAG atoms. ADMG/CPDAG/PAG posterior atoms remain refused.",
    },
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect", "TemporalMediationEffect", "ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Frequentist DBN-posterior mixing is 1.7 work. Temporal graph-posterior cells still require the Bayesian envelope combiner (`execute_dbn_posterior_bayesian`).",
    },
    NaRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "General ID (identifier general.id, the only identifier compile.rs wires for a bidirected ADMG) is not compatible with estimator bayesian.gcomp; forcing Bayesian inference on a bidirected ADMG refuses at compile before any estimate is produced, confirmed on an identifiable front-door-shaped ADMG fixture (Study::build/run).",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Dag", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "compile_graph_posterior (analysis/execute/bayesian_path.rs) wires only AverageEffect and TemporalEffect queries against a graph posterior; ConditionalEffect hits its wildcard Unsupported arm, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Distribution requires identifier general.id (or auto) paired with estimator functional.distribution; forcing Bayesian inference selects estimator bayesian.gcomp, an incompatible pair refused at compile before any estimate, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "PathSpecific requires identifier path_specific.natural (or auto) paired with estimator functional.effect; forcing Bayesian inference selects estimator bayesian.gcomp, an incompatible pair refused at compile before any estimate, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "compile_graph_posterior wires only AverageEffect and TemporalEffect queries against a graph posterior; TemporalMediationEffect (query axis Mediation on a TemporalDag) hits its wildcard Unsupported arm, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: None,
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Graph-posterior response is a contract choice, not typed impossibility: the ATE envelope (retained unidentified mass) is the same object a curve arm would use. This cut does not license a response mixture.",
    },
    NaRule {
        queries: Some(&["ResponseCurve", "InterventionResponse"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "ResponseCurve/InterventionResponse have no class-aware identifier on TemporalCpdag/TemporalPag.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Cpdag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries execute only on a supplied static Dag; a directly supplied Cpdag hits the same static-Dag requirement (Admg/Pag explicit already named above).",
    },
    NaRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg", "Cpdag", "Pag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_graph_posterior_bayesian is Dag-shaped; Admg/Cpdag/Pag posterior atoms are not mixed into an ATE envelope.",
    },
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Class-aware TemporalCpdag/TemporalPag pulse is the Frequentist generalized-adjustment envelope; a Bayesian envelope combiner for temporal incomplete classes is 1.7 work.",
    },
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_dbn_posterior_bayesian is TemporalDag-shaped; TemporalCpdag/TemporalPag posterior atoms are not mixed into a temporal envelope.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Cpdag", "Admg", "Pag"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Query-native functional validation requires a Dag.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Identified discrete path and distribution functionals have no Bayesian evaluator; accepted structure does not supply a posterior estimator.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: Some(&["none"]),
        reason: "Licensed derivative cells are Frequentist explicit or accepted Dag at validation none; Bayesian derivatives remain 1.7 work.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Graph-posterior derivative mixtures are not staged; the licensed derivative cells are Frequentist explicit or accepted Dag at validation none.",
    },
    NaRule {
        queries: Some(&["MediationEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Static natural mediation is Frequentist; a Bayesian mediation estimator is 1.7 work.",
    },
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["accepted", "graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Staged counterfactuals require an explicit Dag; accepted and graph-posterior structures are refused.",
    },
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Counterfactuals are Frequentist abduction-action-prediction; a posterior over mechanisms is 1.7 work.",
    },
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: Some(&["Dag"]),
        structures: None,
        inferences: None,
        validations: Some(&["cheap", "full"]),
        reason: "Counterfactual cheap/full are not licensed; there is no native ITE refuter suite and ATE refuters do not apply.",
    }
];

pub static ALLOWED_RULES: &[AllowedRule] = &[

];

pub static LICENSED: &[LicensedCell] = &[
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalCpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalPag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Admg",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Cpdag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Pag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "PulseEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "SustainedEffect",
        graph_class: "TemporalDag",
        structure: "graph_posterior",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "cheap",
    },
    LicensedCell {
        query: "TemporalMediationEffect",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "TemporalDag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "PointDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PointDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "Elasticity",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "Elasticity",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SemiElasticity",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "SemiElasticity",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "DirectionalDerivative",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "DirectionalDerivative",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseJacobian",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseJacobian",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "MediationEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "Counterfactual",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    }
];
