//! Generated from `parity/support_graphless.toml`; do not edit by hand.
#[allow(clippy::struct_excessive_bools)] // One flat support row; the requires_* flags are independent gates.
pub(super) struct GraphlessLicenseRow {
    pub(super) family: &'static str,
    pub(super) design: &'static str,
    pub(super) method: &'static str,
    pub(super) inference_claim: &'static str,
    pub(super) assignment_unit: &'static str,
    pub(super) known_truth_test: &'static str,
    pub(super) retained_route_test: &'static str,
    pub(super) limitations: &'static str,
    pub(super) min_rows: usize,
    pub(super) min_assignment_units_per_arm: usize,
    pub(super) min_blocks: usize,
    pub(super) min_block_arm: usize,
    pub(super) min_factorial_cell: usize,
    pub(super) min_action_rows: usize,
    pub(super) min_reported_intervals: usize,
    pub(super) min_policy_matches: usize,
    pub(super) min_reference_matches: usize,
    pub(super) min_bin_rows: usize,
    pub(super) min_bin_arm_rows: usize,
    pub(super) min_group_rows: usize,
    pub(super) min_group_arm_rows: usize,
    pub(super) min_local_rows: usize,
    pub(super) min_effective_sample_size: f64,
    pub(super) min_dose_density: f64,
    pub(super) max_normalized_weight: f64,
    pub(super) max_covariates: usize,
    pub(super) min_probability: f64,
    pub(super) all_reported_intervals: bool,
    pub(super) requires_uncoupled_constraints: bool,
    pub(super) requires_disjoint_nuisance_training: bool,
    pub(super) requires_rank_ownership: bool,
    pub(super) requires_balanced_sequences: bool,
    pub(super) requires_known_density: bool,
}
pub(super) const LICENSES: &[GraphlessLicenseRow] = &[
    GraphlessLicenseRow {
        family: "continuous_dose_policy",
        design: "fixed_group_kernel",
        method: "inverse_density_kernel_paired_scores",
        inference_claim: "policy_reference_incremental_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/continuous_dose.rs::fixed_group_dose_policy_support_boundary_covers_known_truth",
        retained_route_test: "crates/antecedent/tests/continuous_dose_policy_route.rs::retained_fixed_dose_policy_intervals_round_trip_and_refuse_tampering",
        limitations: "Fixed pre-outcome group-to-dose policy and reference with known correct observed-dose density, independent subjects, conditional exchangeability, at least 600 evaluation rows and 300 per group, 80 local rows, effective sample size at least 50, maximum normalized local weight 0.05, minimum density 0.2, positive paired score variance, and all three pointwise 95% intervals. Values are for the stated kernel-smoothed interventions, not exact-dose potential outcomes or simultaneous coverage.",
        min_rows: 600,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 3,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 300,
        min_group_arm_rows: 0,
        min_local_rows: 80,
        min_effective_sample_size: 50.0,
        min_dose_density: 0.2,
        max_normalized_weight: 0.05,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: true,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: true,
    },
    GraphlessLicenseRow {
        family: "difference_in_differences",
        design: "panel_2x2",
        method: "cluster_change_scores_cr1",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "cluster",
        known_truth_test: "crates/antecedent/tests/panel_did_interval_calibration.rs::retained_panel_did_cluster_normal_interval_covers_parallel_trends_truth",
        retained_route_test: "crates/antecedent/tests/panel_did_route.rs::supported_panel_did_interval_round_trips_and_rejects_fabrication",
        limitations: "Balanced two-period panel DiD with stable treatment, one pre and post outcome per subject, clusters nested within treatment arms, at least 30 independent clusters per arm, positive CR1 score variation, and a published pointwise 95% normal interval. Parallel untreated trends and no anticipation are declared, not tested by two periods. No staggered or augmented DiD inherits this row.",
        min_rows: 0,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "difference_in_differences",
        design: "repeated_cross_section_2x2",
        method: "four_cell_cluster_scores_cr1",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "cluster",
        known_truth_test: "crates/antecedent/tests/panel_did_interval_calibration.rs::retained_repeated_cross_section_did_interval_covers_parallel_trends_truth",
        retained_route_test: "crates/antecedent/tests/panel_did_route.rs::supported_repeated_cross_section_interval_round_trips_and_rejects_fabrication",
        limitations: "Repeated cross-section 2×2 DiD with unique subjects, clusters nested within treatment groups, at least 30 distinct independent clusters in every group-by-period cell, positive CR1 score variation, and a published pointwise 95% normal interval. Parallel untreated trends and no anticipation are declared. No panel, staggered, or augmented DiD inherits this row.",
        min_rows: 0,
        min_assignment_units_per_arm: 30,
        min_blocks: 4,
        min_block_arm: 30,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "longitudinal_regime",
        design: "known_sequential_randomized_three_period",
        method: "subject_excluded_q_sequential_dr_scores",
        inference_claim: "conditional_q_pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/longitudinal_regime.rs::three_period_excluded_fold_q_interval_covers_randomized_truth",
        retained_route_test: "crates/antecedent/tests/longitudinal_regime_route.rs::three_period_sequential_dr_interval_round_trips_and_refuses_uncalibrated_horizon",
        limitations: "Known sequential randomization over three periods with independent subjects and caller-declared subject-excluded fold Q predictions on disjoint folds. Requires at least 800 subjects, at least 600 observed outcomes, at least 60 subjects whose realized treatment matches the evaluated regime across all three periods, per-period action probability at least 0.5, conditional censoring survival at least 0.95, and an actually published pointwise 95% interval. The single normal interval is conditional on the declared Q law; Q training is not verified. Four or more periods, fitted-Q uncertainty, g-formula, and MSM intervals are not licensed by this row.",
        min_rows: 800,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.5,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: true,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "longitudinal_regime",
        design: "known_sequential_randomized_two_period",
        method: "subject_excluded_q_sequential_dr_scores",
        inference_claim: "conditional_q_pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/longitudinal_regime.rs::subject_excluded_fold_q_sequential_dr_scores_cover_randomized_truth",
        retained_route_test: "crates/antecedent/tests/longitudinal_regime_route.rs::two_period_sequential_dr_graphless_license_round_trips_and_refuses_forgery",
        limitations: "Known sequential randomization over two periods with independent subjects and caller-declared subject-excluded fold Q predictions on disjoint folds. Requires at least 300 subjects, at least 200 observed outcomes, at least 50 subjects whose realized treatment matches the evaluated regime across both periods, per-period action probability at least 0.4, conditional censoring survival at least 0.85, and an actually published pointwise 95% interval. The single normal interval is conditional on the declared Q law; Q training is not verified. Longer histories, fitted-Q uncertainty, g-formula, and MSM intervals are not licensed by this row.",
        min_rows: 300,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.4,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: true,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "policy_value",
        design: "binary_aipw",
        method: "fixed_held_out_randomized_aipw_scores",
        inference_claim: "paired_policy_incremental_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/policy_value.rs::held_out_aipw_and_constrained_multi_action_intervals_cover_known_values",
        retained_route_test: "crates/antecedent/tests/policy_value_route.rs::retained_held_out_policy_intervals_round_trip_and_crossfit_stays_point_only",
        limitations: "Fixed binary policy and reference on 300 independent evaluation subjects under known 0.5 Bernoulli assignment, outcome nuisance predictions trained on caller-declared disjoint subjects, at least 10 policy and reference matches, uncoupled recommendations, positive paired score variance, and both pointwise 95% intervals. Cross-fitted nuisance ownership and learned policies remain outside this row.",
        min_rows: 300,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 2,
        min_policy_matches: 10,
        min_reference_matches: 10,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.5,
        all_reported_intervals: true,
        requires_uncoupled_constraints: true,
        requires_disjoint_nuisance_training: true,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "policy_value",
        design: "binary_aipw_uplift",
        method: "fixed_held_out_randomized_aipw_frozen_rank_scores",
        inference_claim: "paired_policy_incremental_and_all_uplift_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/policy_value.rs::held_out_aipw_and_constrained_multi_action_intervals_cover_known_values",
        retained_route_test: "crates/antecedent/tests/policy_value_route.rs::retained_held_out_uplift_intervals_round_trip_and_refuse_forged_bounds",
        limitations: "Fixed binary AIPW policy with disjoint nuisance training and frozen ranked uplift bins with separate declared ranking training IDs, known 0.5 Bernoulli assignment, at least 300 independent subjects and 50 observed subjects per arm in every bin, and all scalar and bin pointwise 95% intervals published. No cross-fitted or simultaneous guarantee.",
        min_rows: 0,
        min_assignment_units_per_arm: 50,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 3,
        min_policy_matches: 10,
        min_reference_matches: 10,
        min_bin_rows: 300,
        min_bin_arm_rows: 50,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.5,
        all_reported_intervals: true,
        requires_uncoupled_constraints: true,
        requires_disjoint_nuisance_training: true,
        requires_rank_ownership: true,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "policy_value",
        design: "binary_ipw",
        method: "fixed_randomized_ipw_scores",
        inference_claim: "paired_policy_incremental_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/policy_value.rs::pointwise_policy_interval_repeated_sampling_coverage",
        retained_route_test: "crates/antecedent/tests/policy_value_route.rs::retained_held_out_policy_intervals_round_trip_and_crossfit_stays_point_only",
        limitations: "Fixed binary policy and reference on independent held-out subjects with known 0.5 Bernoulli assignment, at least 120 evaluation rows and 10 realized policy and reference matches, uncoupled recommendations, positive paired score variance, and both policy-value and incremental-value pointwise 95% intervals. No learned-policy inference or simultaneous claim.",
        min_rows: 120,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 2,
        min_policy_matches: 10,
        min_reference_matches: 10,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.5,
        all_reported_intervals: true,
        requires_uncoupled_constraints: true,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "policy_value",
        design: "binary_ipw_uplift",
        method: "fixed_randomized_ipw_frozen_rank_scores",
        inference_claim: "paired_policy_incremental_and_all_uplift_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/policy_value.rs::held_out_uplift_bin_intervals_cover_fixed_rank_truth",
        retained_route_test: "crates/antecedent/tests/policy_value_route.rs::retained_held_out_uplift_intervals_round_trip_and_refuse_forged_bounds",
        limitations: "Fixed binary IPW policy plus frozen ranked uplift bins, known 0.5 Bernoulli assignment, declared ranking training IDs disjoint from evaluation IDs, at least 300 independent subjects and 50 observed subjects per arm in every bin, and all scalar and bin pointwise 95% intervals published. No simultaneous top-k band or ranking-model guarantee.",
        min_rows: 0,
        min_assignment_units_per_arm: 50,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 3,
        min_policy_matches: 10,
        min_reference_matches: 10,
        min_bin_rows: 300,
        min_bin_arm_rows: 50,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.5,
        all_reported_intervals: true,
        requires_uncoupled_constraints: true,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: true,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "policy_value",
        design: "multi_action_ipw",
        method: "fixed_randomized_multi_action_ipw_scores",
        inference_claim: "paired_policy_incremental_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/policy_value.rs::held_out_aipw_and_constrained_multi_action_intervals_cover_known_values",
        retained_route_test: "crates/antecedent/tests/policy_value_route.rs::multi_action_intervals_require_nonbinding_global_constraints",
        limitations: "Fixed multi-action policy and reference on 300 independent randomized subjects with known action probabilities at least 0.2, 10 realized policy and reference matches, uncoupled capacities and budgets, positive paired score variance, and both pointwise 95% value intervals. No action-specific CATE claim in this row.",
        min_rows: 300,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 50,
        min_reported_intervals: 2,
        min_policy_matches: 10,
        min_reference_matches: 10,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.2,
        all_reported_intervals: true,
        requires_uncoupled_constraints: true,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "policy_value",
        design: "multi_action_ipw_cate",
        method: "fixed_randomized_multi_action_ipw_fixed_group_scores",
        inference_claim: "paired_policy_incremental_and_all_cate_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/policy_value.rs::boundary_probability_multi_action_cate_intervals_cover_known_truth",
        retained_route_test: "crates/antecedent/tests/policy_value_route.rs::multi_action_intervals_require_nonbinding_global_constraints",
        limitations: "Fixed multi-action policy plus pre-treatment baseline groups declared before outcomes, known action probabilities at least 0.2, at least 300 independent subjects and 50 observed subjects in each compared arm per group, uncoupled constraints, and all scalar and group/action pointwise 95% intervals published. No fitted CATE model or simultaneous group coverage.",
        min_rows: 300,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 50,
        min_reported_intervals: 3,
        min_policy_matches: 10,
        min_reference_matches: 10,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 300,
        min_group_arm_rows: 50,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.2,
        all_reported_intervals: true,
        requires_uncoupled_constraints: true,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "bernoulli",
        method: "ancova_hc0",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/ancova.rs::bernoulli_ancova_hc0_covers_known_finite_population_effect",
        retained_route_test: "crates/antecedent/tests/randomized_precision_intervals.rs::supported_ancova_and_fixed_cuped_intervals_round_trip_and_refuse_forgery",
        limitations: "Independent Bernoulli binary ITT with one or two pre-assignment ANCOVA covariates, a common declared probability from 0.2 through 0.8, 400 rows, 30 observed rows per arm, positive HC0 variance, and a published pointwise 95% interval. Six 2,000-allocation fixtures cover one and two covariates at probabilities 0.2, 0.5, and 0.8; three or more covariates remain point-only.",
        min_rows: 400,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 2,
        min_probability: 0.2,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "bernoulli",
        method: "fixed_cuped_ht_score",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_scores.rs::fixed_preassignment_cuped_score_covers_original_itt",
        retained_route_test: "crates/antecedent/tests/randomized_precision_intervals.rs::supported_ancova_and_fixed_cuped_intervals_round_trip_and_refuse_forgery",
        limitations: "Independent Bernoulli binary ITT adjusted by one pre-assignment covariate with a coefficient fixed outside these outcomes, known probabilities from 0.2 through 0.8 on every row, 400 rows, 30 observed assignments per arm, positive independent-unit score variance, and a published pointwise 95% interval. Four 2,000-allocation fixtures cover both probability boundaries, the midpoint, and varying probabilities.",
        min_rows: 400,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.2,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "bernoulli",
        method: "independent_action_ht_score",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_scores.rs::independent_bernoulli_and_multi_arm_coverage",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Independent Bernoulli binary ITT with known probabilities at least 0.2 in both arms on every row, 400 rows, 30 realized assignments per arm, and a published positive-variance pointwise 95% score interval. Adjustments and CACE/LATE do not inherit this row.",
        min_rows: 400,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.2,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "cluster",
        method: "neyman_unit_weighted_cluster_totals",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "cluster",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::cluster_interval_support_boundary_covers_known_itt",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known complete cluster assignment, independent clusters, binary unit-weighted ITT, at least 30 clusters per arm, and an actually published interval (positive realized variance). Conservative cluster-total variance and a pointwise 95% normal interval; no observational network exposure or other assignment design is licensed by this row.",
        min_rows: 0,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "complete",
        method: "neyman_difference_in_means",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::complete_interval_support_boundary_covers_known_itt",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known complete assignment, independent units, binary ITT, at least 30 units per arm, and an actually published interval (positive realized variance). Conservative Neyman variance and a pointwise 95% normal interval; no simultaneous interval, CACE, adjustment, or other assignment design is licensed by this row.",
        min_rows: 0,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "factorial_2x2",
        method: "fixed_cell_neyman_contrasts",
        inference_claim: "three_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::factorial_cell_randomization_covers_three_known_pointwise_effects",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known fixed-cell 2×2 randomization with at least 30 units in every cell and published positive-variance intervals for both main effects and the interaction. Each 95% interval is pointwise; joint or simultaneous coverage is not licensed.",
        min_rows: 0,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 30,
        min_action_rows: 0,
        min_reported_intervals: 3,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: true,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "multi_arm",
        method: "independent_action_ht_scores",
        inference_claim: "all_action_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_scores.rs::independent_bernoulli_and_multi_arm_coverage",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Independent known-probability assignment to at least three actions, 400 rows, at least 30 realized assignments to every action, probabilities at least 0.2 for every action on every row, and a published interval for every action-versus-reference contrast. The intervals are separate pointwise 95% claims; simultaneous coverage is not licensed.",
        min_rows: 400,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 30,
        min_reported_intervals: 2,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.2,
        all_reported_intervals: true,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "stratified",
        method: "blocked_neyman_difference_in_means",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::blocked_randomization_covers_known_itt_and_withholds_sparse_blocks",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known independent complete assignment within at least four blocks, at least 15 units in every block arm and 60 per overall arm, and a published positive-variance pointwise 95% interval. This row licenses the block-weighted ITT only.",
        min_rows: 0,
        min_assignment_units_per_arm: 60,
        min_blocks: 4,
        min_block_arm: 15,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "switchback",
        method: "independent_sequence_ht_score",
        inference_claim: "pointwise_95_student_interval",
        assignment_unit: "sequence",
        known_truth_test: "crates/antecedent-estimate/tests/switchback_calibration.rs::switchback_student_interval_covers_known_truth",
        retained_route_test: "crates/antecedent/tests/switchback_interval_route.rs::supported_switchback_interval_round_trips_and_rejects_forgery",
        limitations: "Switchback unit-period HT ITT with at least 30 independent assignment sequences of equal observed period count, at least 30 realized periods in each arm globally, known marginal probabilities at least 0.2 for each arm on every row, positive independent-sequence sandwich variance, and a published pointwise 95% Student interval. No carryover and no between-sequence interference are declared, untestable identification assumptions. Six unconditional 2,000-allocation known-truth fixtures include probability boundaries, varying probabilities, and serial assignment within sequences. Unequal schedules and sparse or weak arm support remain point-only.",
        min_rows: 0,
        min_assignment_units_per_arm: 0,
        min_blocks: 30,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 30,
        min_reported_intervals: 1,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.2,
        all_reported_intervals: false,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: true,
        requires_known_density: false,
    },
    GraphlessLicenseRow {
        family: "survival",
        design: "two_arm_individual_randomized",
        method: "arm_stratified_subject_bootstrap_product_limit",
        inference_claim: "rmst_and_horizon_survival_pointwise_95_percentile_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/survival.rs::randomized_survival_scalar_bootstrap_support_boundary_covers_known_truth",
        retained_route_test: "crates/antecedent/tests/survival_route.rs::licensed_survival_scalar_intervals_round_trip_and_refuse_forgery",
        limitations: "Individually randomized independent subjects, at least 120 observed subjects per arm, marginal independent right censoring within arm, no delayed entry or caller-supplied censoring weights, at least 299 valid arm-stratified subject-bootstrap draws, and both pointwise 95% scalar intervals for RMST and survival difference at the fixed horizon. Two 2,000-study known-truth coverage checks run at 120 subjects per arm and 299 draws. The row does not license a simultaneous curve band, conditional censoring, delayed entry, or competing-risk incidence.",
        min_rows: 240,
        min_assignment_units_per_arm: 120,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 2,
        min_policy_matches: 0,
        min_reference_matches: 0,
        min_bin_rows: 0,
        min_bin_arm_rows: 0,
        min_group_rows: 0,
        min_group_arm_rows: 0,
        min_local_rows: 0,
        min_effective_sample_size: 0.0,
        min_dose_density: 0.0,
        max_normalized_weight: 0.0,
        max_covariates: 0,
        min_probability: 0.0,
        all_reported_intervals: true,
        requires_uncoupled_constraints: false,
        requires_disjoint_nuisance_training: false,
        requires_rank_ownership: false,
        requires_balanced_sequences: false,
        requires_known_density: false,
    },
];
