//! Generated from parity/support_graphless.toml; do not edit by hand.
pub(super) struct GraphlessLicenseRow {
    pub(super) family: &'static str,
    pub(super) design: &'static str,
    pub(super) method: &'static str,
    pub(super) inference_claim: &'static str,
    pub(super) assignment_unit: &'static str,
    pub(super) known_truth_test: &'static str,
    pub(super) retained_route_test: &'static str,
    pub(super) limitations: &'static str,
    pub(super) min_rows: usize,
    pub(super) min_assignment_units_per_arm: usize,
    pub(super) min_blocks: usize,
    pub(super) min_block_arm: usize,
    pub(super) min_factorial_cell: usize,
    pub(super) min_action_rows: usize,
    pub(super) min_reported_intervals: usize,
    pub(super) min_probability: f64,
    pub(super) all_reported_intervals: bool,
}
pub(super) const LICENSES: &[GraphlessLicenseRow] = &[
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "bernoulli",
        method: "independent_action_ht_score",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_scores.rs::independent_bernoulli_and_multi_arm_coverage",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Independent Bernoulli binary ITT with known probabilities at least 0.2 in both arms on every row, 400 rows, 30 realized assignments per arm, and a published positive-variance pointwise 95% score interval. Fixed CUPED, ANCOVA, CACE/LATE, and lower-probability designs are outside this license.",
        min_rows: 400,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_probability: 0.2,
        all_reported_intervals: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "cluster",
        method: "neyman_unit_weighted_cluster_totals",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "cluster",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::cluster_interval_support_boundary_covers_known_itt",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known complete cluster assignment, independent clusters, binary unit-weighted ITT, at least 30 clusters per arm, and an actually published interval (positive realized variance). Conservative cluster-total variance and a pointwise 95% normal interval; no observational network exposure or other assignment design is licensed by this row.",
        min_rows: 0,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_probability: 0.0,
        all_reported_intervals: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "complete",
        method: "neyman_difference_in_means",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::complete_interval_support_boundary_covers_known_itt",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known complete assignment, independent units, binary ITT, at least 30 units per arm, and an actually published interval (positive realized variance). Conservative Neyman variance and a pointwise 95% normal interval; no simultaneous interval, CACE, adjustment, or other assignment design is licensed by this row.",
        min_rows: 0,
        min_assignment_units_per_arm: 30,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_probability: 0.0,
        all_reported_intervals: false,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "factorial_2x2",
        method: "fixed_cell_neyman_contrasts",
        inference_claim: "three_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::factorial_cell_randomization_covers_three_known_pointwise_effects",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known fixed-cell 2×2 randomization with at least 30 units in every cell and published positive-variance intervals for both main effects and the interaction. Each 95% interval is pointwise; joint or simultaneous coverage is not licensed.",
        min_rows: 0,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 30,
        min_action_rows: 0,
        min_reported_intervals: 3,
        min_probability: 0.0,
        all_reported_intervals: true,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "multi_arm",
        method: "independent_action_ht_scores",
        inference_claim: "all_action_pointwise_95_normal_intervals",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_scores.rs::independent_bernoulli_and_multi_arm_coverage",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Independent known-probability assignment to at least three actions, 400 rows, at least 30 realized assignments to every action, probabilities at least 0.2 for every action on every row, and a published interval for every action-versus-reference contrast. The intervals are separate pointwise 95% claims; simultaneous coverage is not licensed.",
        min_rows: 400,
        min_assignment_units_per_arm: 0,
        min_blocks: 0,
        min_block_arm: 0,
        min_factorial_cell: 0,
        min_action_rows: 30,
        min_reported_intervals: 2,
        min_probability: 0.2,
        all_reported_intervals: true,
    },
    GraphlessLicenseRow {
        family: "randomized_effect",
        design: "stratified",
        method: "blocked_neyman_difference_in_means",
        inference_claim: "pointwise_95_normal_interval",
        assignment_unit: "unit",
        known_truth_test: "crates/antecedent-estimate/src/randomized_neyman.rs::blocked_randomization_covers_known_itt_and_withholds_sparse_blocks",
        retained_route_test: "crates/antecedent/tests/randomized_trial_route.rs::calibrated_randomized_intervals_round_trip_and_reject_tampering",
        limitations: "Known independent complete assignment within at least four blocks, at least 15 units in every block arm and 60 per overall arm, and a published positive-variance pointwise 95% interval. This row licenses the block-weighted ITT only.",
        min_rows: 0,
        min_assignment_units_per_arm: 60,
        min_blocks: 4,
        min_block_arm: 15,
        min_factorial_cell: 0,
        min_action_rows: 0,
        min_reported_intervals: 1,
        min_probability: 0.0,
        all_reported_intervals: false,
    },
];
