//! Generated from `parity/support_*.toml`. Do not edit.

#![allow(missing_docs)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Copy, Debug)]
pub struct NaRule {
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct AllowedRule {
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
    pub parent: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct LicensedCell {
    pub query: &'static str,
    pub graph_class: &'static str,
    pub structure: &'static str,
    pub inference: &'static str,
    pub validation: &'static str,
}

pub static NA_RULES: &[NaRule] = &[
    NaRule {
        queries: Some(&["PulseEffect", "SustainedEffect", "TemporalMediationEffect"]),
        graph_classes: Some(&["Dag", "Admg", "Cpdag", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Temporal contrast queries require a temporal graph class.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "AverageEffect", "ConditionalEffect", "Counterfactual", "DirectionalDerivative", "Elasticity", "InterventionalDistribution", "InterventionResponse", "PathSpecificEffect", "PointDerivative", "ResponseCurve", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Static queries are not a temporal-graph cell; use PulseEffect or SustainedEffect.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "InterventionResponse", "PointDerivative", "ResponseCurve", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: None,
        structures: Some(&["graph_posterior"]),
        inferences: None,
        validations: None,
        reason: "Structural uncertainty around curves is contrast-only; graph-posterior mixtures do not license a response cell.",
    },
    NaRule {
        queries: Some(&["TransportQuery", "InterferenceQuery"]),
        graph_classes: Some(&["TemporalDag", "TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "Stage transport and interference queries are not a temporal-graph cell.",
    }
];

pub static CLOSED_RULES: &[NaRule] = &[
    NaRule {
        queries: Some(&["Counterfactual"]),
        graph_classes: None,
        structures: None,
        inferences: None,
        validations: None,
        reason: "Counterfactual is not on the staged handle.",
    },
    NaRule {
        queries: Some(&["AverageDerivative", "DirectionalDerivative", "Elasticity", "PointDerivative", "ResponseJacobian", "SemiElasticity"]),
        graph_classes: None,
        structures: None,
        inferences: None,
        validations: None,
        reason: "Derivative cells are not licensed; only ResponseCurve on a Dag is staged.",
    },
    NaRule {
        queries: Some(&["ResponseCurve"]),
        graph_classes: Some(&["Pag", "Cpdag", "Admg"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "ResponseCurve is licensed only on a Dag.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect", "InterventionalDistribution"]),
        graph_classes: None,
        structures: Some(&["graph_posterior", "accepted"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries are licensed only as explicit Dag cells; accepted and graph-posterior structures are not staged.",
    },
    NaRule {
        queries: Some(&["MediationEffect"]),
        graph_classes: None,
        structures: None,
        inferences: None,
        validations: None,
        reason: "MediationEffect is not on the staged handle.",
    },
    NaRule {
        queries: Some(&["SustainedEffect"]),
        graph_classes: None,
        structures: None,
        inferences: None,
        validations: None,
        reason: "SustainedEffect is not on the staged handle.",
    },
    NaRule {
        queries: Some(&["TransportQuery", "InterferenceQuery"]),
        graph_classes: None,
        structures: None,
        inferences: None,
        validations: None,
        reason: "Stage transport and interference APIs are not licensed analyze cells; sID outside the implemented subset is NotCertified.",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Cpdag", "Admg", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "ConditionalEffect compiles only against a supplied static Dag; Cpdag/Admg/Pag have no ConditionalEffect compile arm.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Admg", "Pag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries execute only on a supplied static Dag; a directly supplied Admg/Pag hits the same static-Dag requirement (accepted/graph-posterior Admg and Pag are already closed above).",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Admg", "Pag"]),
        structures: Some(&["explicit"]),
        inferences: None,
        validations: None,
        reason: "Path and distribution queries execute only on a supplied static Dag; a directly supplied Admg/Pag hits the same static-Dag requirement (accepted/graph-posterior Admg and Pag are already closed above).",
    },
    NaRule {
        queries: Some(&["InterventionResponse"]),
        graph_classes: Some(&["Cpdag", "Admg", "Pag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "InterventionResponse executes only on a supplied static Dag, the same requirement ResponseCurve is closed on above; Cpdag/Admg/Pag have no Response compile arm.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: None,
        inferences: None,
        validations: None,
        reason: "TemporalMediationEffect compiles only against a supplied TemporalDag; compile.rs has no Mediation arm for TemporalCpdag/TemporalPag.",
    },
    NaRule {
        queries: None,
        graph_classes: None,
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "Graph-posterior compilation requires Bayesian inference: a graph posterior is a mixture over structures, and only Bayesian inference can combine per-graph effect draws into an envelope.",
    },
    NaRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "General ID (identifier general.id, the only identifier compile.rs wires for a bidirected ADMG) is not compatible with estimator bayesian.gcomp; forcing Bayesian inference on a bidirected ADMG refuses at compile before any estimate is produced, confirmed on an identifiable front-door-shaped ADMG fixture (Study::build/run).",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_conditional (analysis/execute/static_path.rs) hardcodes EstimatorId::ConditionalLinearAdjustment regardless of inference mode; a Bayesian-labeled study silently returns the identical Frequentist estimate (confirmed: Frequentist and Bayesian runs on the same fixture produce a bit-identical ate and estimand.method), so this cell cannot return an honest Bayesian number.",
    },
    NaRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "compile_graph_posterior (analysis/execute/bayesian_path.rs) wires only AverageEffect and TemporalEffect queries against a graph posterior; ConditionalEffect hits its wildcard Unsupported arm, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Distribution requires identifier general.id (or auto) paired with estimator functional.distribution; forcing Bayesian inference selects estimator bayesian.gcomp, an incompatible pair refused at compile before any estimate, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["InterventionResponse"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Response requires identifier response.backdoor paired with a response.* estimator; forcing Bayesian inference selects estimator bayesian.gcomp, an incompatible pair refused at compile before any estimate, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "PathSpecific requires identifier path_specific.natural (or auto) paired with estimator functional.effect; forcing Bayesian inference selects estimator bayesian.gcomp, an incompatible pair refused at compile before any estimate, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["ResponseCurve"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "Response requires identifier response.backdoor paired with a response.* estimator; forcing Bayesian inference selects estimator bayesian.gcomp, an incompatible pair refused at compile before any estimate, confirmed via Study::build/run.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_temporal_mediation (analysis/execute/temporal_path.rs) hardcodes EstimatorId::TemporalMediation regardless of inference mode; a Bayesian-labeled study silently returns the identical Frequentist estimate (confirmed: Frequentist and Bayesian runs on the same fixture produce a bit-identical mediation estimate and estimand.method), so this cell cannot return an honest Bayesian number.",
    },
    NaRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "compile_graph_posterior wires only AverageEffect and TemporalEffect queries against a graph posterior; TemporalMediationEffect (query axis Mediation on a TemporalDag) hits its wildcard Unsupported arm, confirmed via Study::build/run.",
    }
];

pub static ALLOWED_RULES: &[AllowedRule] = &[
    AllowedRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Bayesian"]),
        validations: Some(&["cheap", "full"]),
        reason: "Same BayesianGComputationAte path as the licensed Dag/Bayesian/none cell; cheap and full only add refuter suites on top of the same estimate. Not licensed because the matrix pins the estimate, not the refuter suite, on this axis; validation = cheap/full ride the licensed cell's own fixture rather than a separate known-truth pin.",
        parent: "AverageEffect Dag explicit/accepted Bayesian none (licensed)",
    },
    AllowedRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_graph_posterior_bayesian identifies and fits every posterior atom into a Bayesian effect envelope; genuinely runs (crates/antecedent/tests/manufacturing_temporal.rs exercises the sibling TemporalEffect case end-to-end, and analysis/execute/mod.rs's own tests build a graph-posterior study under Bayesian inference). Not licensed because a graph posterior has no single known-truth fixture to pin -- the atoms it mixes vary per discovery run.",
        parent: "AverageEffect Dag explicit/accepted Bayesian none (licensed)",
    },
    AllowedRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Admg"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "execute_admg runs general ID + FunctionalEffect whenever the ADMG carries a bidirected edge (compile.rs's Admg arm, dispatch.rs's execute() Admg arm); confirmed end-to-end on an identifiable front-door-shaped ADMG fixture. NotIdentified on a non-identifiable ADMG is a normal per-graph identification outcome, not a wiring failure. Not licensed because there is no known-truth fixture pinning general-ID ADMG estimates the way the Dag/Pag families are pinned.",
        parent: "AverageEffect Dag explicit/accepted Frequentist none (licensed); mirrors the AverageEffect Pag family below",
    },
    AllowedRule {
        queries: Some(&["AverageEffect"]),
        graph_classes: Some(&["Pag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: None,
        reason: "Generalized adjustment on a PAG (execute_pag) is fully wired for both Frequentist and Bayesian inference and every validation suite; confirmed end-to-end. Not licensed because PAG ATE re-identifies per click against the supplied PAG (no staged handle, no cell-shaped known-truth fixture the way the Dag family is pinned).",
        parent: "AverageEffect Dag explicit/accepted Frequentist/Bayesian none (licensed)",
    },
    AllowedRule {
        queries: Some(&["ConditionalEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Frequentist"]),
        validations: Some(&["cheap", "full"]),
        reason: "Same ConditionalLinearAdjustment path as the licensed Dag/Frequentist/none cell; cheap and full only add refuter suites on top of the same estimate; confirmed end-to-end. Not licensed because the matrix pins the estimate, not the refuter suite, on this axis.",
        parent: "ConditionalEffect Dag explicit/accepted Frequentist none (licensed)",
    },
    AllowedRule {
        queries: Some(&["InterventionalDistribution"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit"]),
        inferences: Some(&["Frequentist"]),
        validations: Some(&["cheap", "full"]),
        reason: "Same general.id + functional.distribution path as the licensed Dag/explicit/Frequentist/none cell; cheap and full only add refuter suites; confirmed end-to-end on a discrete fixture (functional.distribution discretizes every column and caps unique levels). Not licensed because the matrix pins identification, not the refuter suite, on this axis.",
        parent: "InterventionalDistribution Dag explicit Frequentist none (licensed)",
    },
    AllowedRule {
        queries: Some(&["InterventionResponse"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Frequentist"]),
        validations: Some(&["cheap", "full"]),
        reason: "Same response.intervention_gcomp path as the licensed Dag/Frequentist/none cell; cheap and full only add refuter suites; confirmed end-to-end. Not licensed because the matrix pins the estimate, not the refuter suite, on this axis.",
        parent: "InterventionResponse Dag explicit/accepted Frequentist none (licensed)",
    },
    AllowedRule {
        queries: Some(&["PathSpecificEffect"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit"]),
        inferences: Some(&["Frequentist"]),
        validations: Some(&["cheap", "full"]),
        reason: "Same PathSpecificNatural + FunctionalEffect path as the licensed Dag/explicit/Frequentist/none cell; cheap and full only add refuter suites; confirmed end-to-end on a discrete fixture (this path also discretizes columns). Not licensed because the matrix pins identification, not the refuter suite, on this axis.",
        parent: "PathSpecificEffect Dag explicit Frequentist none (licensed)",
    },
    AllowedRule {
        queries: Some(&["PulseEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: None,
        validations: None,
        reason: "Temporal backdoor (compile_logical_temporal_effect_classified / execute_temporal) is fully wired for both Frequentist and Bayesian inference and every validation suite; confirmed end-to-end for Frequentist and Bayesian under none/cheap validation (full needs a longer complete series than the probe fixture supplied, same mechanism otherwise). Not licensed because there is no staged handle for the temporal path and no cell-shaped known-truth fixture pinning it the way the static AverageEffect family is pinned.",
        parent: "AverageEffect Dag explicit/accepted Frequentist/Bayesian none (licensed); temporal analogue",
    },
    AllowedRule {
        queries: Some(&["PulseEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["graph_posterior"]),
        inferences: Some(&["Bayesian"]),
        validations: None,
        reason: "execute_dbn_posterior_bayesian mixes a DBN graph posterior into a Bayesian temporal effect envelope; crates/antecedent/tests/manufacturing_temporal.rs's manufacturing_dbn_posterior_bayesian_envelope test runs this exact cell end-to-end. Not licensed because a DBN posterior has no single known-truth fixture -- the atoms it mixes vary per discovery run.",
        parent: "PulseEffect TemporalDag explicit/accepted Frequentist/Bayesian (allowed, above)",
    },
    AllowedRule {
        queries: Some(&["PulseEffect"]),
        graph_classes: Some(&["TemporalCpdag", "TemporalPag"]),
        structures: Some(&["accepted"]),
        inferences: None,
        validations: None,
        reason: "A discovery-accepted TemporalCpdag/TemporalPag with no undirected/circle marks left pending does not always complete to a TemporalDag (try_into_temporal_dag can still fail -- e.g. a resolved-but-bidirected mark a CPDAG/PAG completion review does not reduce to a lagged direction); compile.rs's TemporalCpdag/TemporalPag arms run that same completion attempt and, on success, execute the temporal backdoor exactly like the TemporalDag family. On failure they surface CausalError::Compile (Python's CausalCompileError), never a silent or mislabeled number. J-PCMCI+/LPCMCI discovery in python/src/temporal_api.rs (accept_temporal_cpdag_review / accept_temporal_pag_review) reaches this cell directly and today; python/tests/test_analyze_discovery.py::test_analyze_discovery_jpcmci_plus_two_env and test_panel_discover_ci_callback.py::test_panel_discover_jpcmci_plus_ci_callback_invoked already tolerate the CausalCompileError outcome as legitimate, alongside a clean estimate. Not licensed because completion success is per-discovered-graph and not staged.",
        parent: "PulseEffect TemporalDag explicit/accepted Frequentist/Bayesian (allowed, above) -- same temporal backdoor, reached via a graph that does not always finish collapsing",
    },
    AllowedRule {
        queries: Some(&["ResponseCurve"]),
        graph_classes: Some(&["Dag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Frequentist"]),
        validations: Some(&["cheap", "full"]),
        reason: "Same response.backdoor + Kennedy-DR path as the licensed Dag/Frequentist/none cell; cheap and full only add refuter suites on top of the same curve; confirmed end-to-end. Not licensed because the matrix pins the curve, not the refuter suite, on this axis.",
        parent: "ResponseCurve Dag explicit/accepted Frequentist none (licensed)",
    },
    AllowedRule {
        queries: Some(&["TemporalMediationEffect"]),
        graph_classes: Some(&["TemporalDag"]),
        structures: Some(&["explicit", "accepted"]),
        inferences: Some(&["Frequentist"]),
        validations: None,
        reason: "execute_temporal_mediation runs TemporalMediationIdentifier + TemporalMediationEstimator end-to-end for every validation suite under Frequentist inference; confirmed end-to-end. Bayesian inference on this cell is deliberately excluded (closed instead, parity/support_closed.toml): execute_temporal_mediation hardcodes EstimatorId::TemporalMediation and never consults inference mode, so a Bayesian-labeled run would silently return the identical Frequentist number. Not licensed because there is no staged handle or known-truth fixture pinning temporal mediation the way the static AverageEffect family is pinned.",
        parent: "TemporalMediationEffect TemporalDag explicit/accepted Frequentist (this row is the running family; Bayesian is closed, not allowed)",
    }
];

pub static LICENSED: &[LicensedCell] = &[
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "cheap",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "full",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ResponseCurve",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Bayesian",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "ConditionalEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "PathSpecificEffect",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionResponse",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "InterventionalDistribution",
        graph_class: "Dag",
        structure: "explicit",
        inference: "Frequentist",
        validation: "none",
    },
    LicensedCell {
        query: "AverageEffect",
        graph_class: "Dag",
        structure: "accepted",
        inference: "Bayesian",
        validation: "none",
    }
];
