"""Package type stub for ``causal``."""

from __future__ import annotations

from . import (
    attribution,
    counterfactual,
    data,
    design,
    discovery,
    estimation,
    extensibility,
    graph,
    inference,
    model,
    query,
    state,
    validation,
)
from ._native import (
    Admg,
    AnomalyScores,
    ArrowLoadInfo,
    AteAnalysisResult,
    CausalAttributionError,
    CausalCompileError,
    CausalCounterfactualError,
    CausalDataError,
    CausalDesignError,
    CausalDiscoveryError,
    CausalError,
    CausalEstimateError,
    CausalGraphError,
    CausalIdentifyError,
    CausalModelError,
    CausalResourceError,
    CausalReviewError,
    CausalSerializationError,
    CausalState,
    CausalStateError,
    CausalUnsupportedError,
    CausalValidateError,
    ChangeAttributionResult,
    Contribution,
    Cpdag,
    Dag,
    DecisionEvaluation,
    DesignRanking,
    DiscoveredLink,
    FeatureRelevance,
    FittedGcm,
    GcmIteResult,
    GcmSampleResult,
    GraphEdge,
    GraphPosterior,
    MechanismChangeDetection,
    MediationEffectsSummary,
    Pag,
    PcmciDiscoveryResult,
    PosteriorArtifact,
    PredictSummary,
    RpcmciDiscoverySummary,
    TemporalCpdag,
    TemporalDag,
    TemporalPag,
    anomaly_attribution,
    attribute_distribution_change,
    attribute_distribution_change_robust,
    attribute_feature_relevance,
    attribute_path_specific,
    attribute_paths,
    attribute_structure_change,
    attribute_unit_change,
    counterfactual_ite,
    dag_from_dot,
    dag_from_gml,
    dag_from_json,
    dag_from_networkx_adjacency,
    dag_from_networkx_node_link,
    dag_to_dot,
    dag_to_gml,
    dag_to_json,
    dag_to_networkx_adjacency,
    dag_to_networkx_node_link,
    decode_model_bundle,
    decode_posterior_artifact,
    encode_model_bundle,
    encode_posterior_artifact,
    fit_gcm,
    load_float64_arrow_c_columns,
    load_float64_columns,
    mechanism_change_detection,
    mediation_effects_summary,
    predict_intervened_summary,
    rank_designs,
    rank_root_causes,
    sample_do,
    sample_interventional_distribution,
)
from .design import evaluate_decision
from .discovery import (
    CiScreenedPosterior,
    DbnPosterior,
    ExactDagPosterior,
    FCI,
    GES,
    JPCMCIPlus,
    LPCMCI,
    LiNGAM,
    NOTEARS,
    OrderMcmc,
    PC,
    PCMCI,
    PCMCIPlus,
    RFCI,
    RPCMCI,
    StructureMcmc,
    discover_ci_screened_posterior,
    discover_dbn_posterior,
    discover_exact_dag_posterior,
    discover_jpcmci_plus,
    discover_lpcmci,
    discover_order_mcmc,
    discover_pc,
    discover_ges,
    discover_lingam,
    discover_notears,
    discover_fci,
    discover_rfci,
    discover_pcmci,
    discover_pcmci_plus,
    discover_rpcmci,
    discover_structure_mcmc,
    two_regime_half_split,
)
from .estimation import AnalysisResult, analyze
from .inference import Bayesian, Frequentist
from .query import (
    AverageEffect,
    InterventionalDistribution,
    PathSpecificEffect,
    PulseEffect,
    SustainedEffect,
)
from .validation import (
    validate_environment_holdout,
    validate_pcmci_alpha_sensitivity,
    validate_pcmci_block_bootstrap,
    validate_pcmci_ci_sensitivity,
    validate_pcmci_false_positive,
    validate_pcmci_lag_sensitivity,
    validate_pcmci_plus_orientation,
    validate_regime_stability,
    validate_synthetic_null_calibration,
)

__version__: str

__all__: list[str]
