"""Package type stub for ``causal``."""

from __future__ import annotations

from . import attribution, counterfactual, data, design, discovery, estimation, graph, inference, model, query, state
from ._native import (
    ArrowLoadInfo,
    AteAnalysisResult,
    CausalAttributionError,
    CausalCompileError,
    CausalCounterfactualError,
    CausalDataError,
    CausalDesignError,
    CausalDiscoveryError,
    CausalError,
    CausalEstimateError,
    CausalGraphError,
    CausalIdentifyError,
    CausalModelError,
    CausalResourceError,
    CausalReviewError,
    CausalSerializationError,
    CausalStateError,
    CausalUnsupportedError,
    CausalValidateError,
    DiscoveredLink,
    GcmIteResult,
    GcmSampleResult,
    GraphEdge,
    MediationEffectsSummary,
    PcmciDiscoveryResult,
    PosteriorArtifact,
    PredictSummary,
    RpcmciDiscoverySummary,
    anomaly_attribution,
    attribute_distribution_change,
    attribute_distribution_change_robust,
    attribute_feature_relevance,
    attribute_path_specific,
    attribute_unit_change,
    counterfactual_ite,
    dag_from_dot,
    dag_from_gml,
    dag_from_json,
    dag_from_networkx_adjacency,
    dag_from_networkx_node_link,
    dag_to_dot,
    dag_to_gml,
    dag_to_json,
    dag_to_networkx_adjacency,
    dag_to_networkx_node_link,
    decode_model_bundle,
    decode_posterior_artifact,
    encode_model_bundle,
    encode_posterior_artifact,
    load_float64_arrow_c_columns,
    load_float64_columns,
    mechanism_change_detection,
    mediation_effects_summary,
    predict_intervened_summary,
    rank_designs,
    sample_do,
    sample_interventional_distribution,
)
from .discovery import (
    JPCMCIPlus,
    LPCMCI,
    PC,
    PCMCI,
    PCMCIPlus,
    RPCMCI,
    discover_jpcmci_plus,
    discover_lpcmci,
    discover_pc,
    discover_pcmci,
    discover_pcmci_plus,
    discover_rpcmci,
)
from .estimation import AnalysisResult, analyze
from .inference import Bayesian, Frequentist
from .query import AverageEffect, PulseEffect, SustainedEffect

__version__: str

__all__: list[str]
