//! Link the extension module and its `cargo test` harness differently.
//!
//! The wheel is a cdylib. On macOS it must allow unresolved Python symbols
//! (`-undefined dynamic_lookup`); the interpreter that loads it provides them.
//! `cargo test` builds a standalone harness of the same crate. 2.0's harness
//! dropped unused Python calls. 2.1 keeps `PyInit__native` live, so the harness
//! has to link libpython. `#[link]` under `cfg(test)` does that without
//! recording the dependency on the cdylib. `rustc-link-arg-tests` does not
//! apply to a cdylib's lib-test harness, so the rpath (Homebrew and framework
//! builds install libpython as `@rpath/...`) is a normal link arg.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-cdylib-link-arg=-undefined");
        println!("cargo:rustc-cdylib-link-arg=dynamic_lookup");
    }

    let config = pyo3_build_config::get();
    let Some(lib_name) = config.lib_name() else {
        return;
    };
    if !config.shared() {
        println!(
            "cargo:warning=antecedent-py tests need a shared libpython; `{lib_name}` is static"
        );
        return;
    }
    if let Some(dir) = config.lib_dir() {
        println!("cargo:rustc-link-search=native={dir}");
        println!("cargo:rustc-link-arg=-Wl,-rpath,{dir}");
    }
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let link = format!(
        "// Generated by build.rs. Do not edit.\n\
         #[link(name = \"{lib_name}\", kind = \"dylib\")]\n\
         unsafe extern \"C\" {{}}\n"
    );
    fs::write(out.join("python_test_link.rs"), link).expect("write python_test_link.rs");
}
