#!/usr/bin/env python3
"""Parse calibration-record JSON lines into parity/coverage_records.toml."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOG_DIR = ROOT / "target" / "calibration-records"
OUT = ROOT / "parity" / "coverage_records.toml"


def main() -> int:
    sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    records = {}
    if not LOG_DIR.is_dir():
        raise SystemExit(f"missing {LOG_DIR}")
    for log in sorted(LOG_DIR.glob("*.log")):
        for line in log.read_text(errors="ignore").splitlines():
            if not line.startswith("calibration-record "):
                continue
            payload = json.loads(line.split(" ", 1)[1])
            rid = payload["id"]
            if rid in records:
                raise SystemExit(f"duplicate record id {rid}")
            payload["calibration_sha"] = sha
            records[rid] = payload
    lines = [
        "# Coverage records bound onto executions at claim time.",
        "# Regenerated by scripts/collect_coverage_records.py from weekly logs.",
        "",
    ]
    for rid in sorted(records):
        rec = records[rid]
        lines.append("[[record]]")
        for key in (
            "id",
            "query",
            "graph_class",
            "inference",
            "estimator",
            "interval_method",
            "se_kind",
            "dgp",
            "n",
            "dependence",
            "nominal",
            "observed",
            "mcse",
            "replicates",
            "boundary",
            "test",
            "calibration_sha",
        ):
            value = rec[key]
            if isinstance(value, bool):
                lines.append(f"{key} = {'true' if value else 'false'}")
            elif isinstance(value, (int, float)) and key != "id":
                lines.append(f"{key} = {value}")
            else:
                lines.append(f'{key} = "{value}"')
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(records)} records to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
