#!/usr/bin/env bash
# Scheduled statistical calibration gate.
# Not part of every-PR unit CI — run locally / before release / weekly GHA.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Coverage tests run 400 replicates each (two-sided level ± 3·MCSE band), so the
# gate builds in release; a debug build is ~50x slower with identical numbers.
run_ignored() {
  local pkg="$1"
  local filter="$2"
  echo "== ${pkg}: ${filter} =="
  cargo test --release -p "$pkg" --lib "$filter" -- --ignored --nocapture
}

echo "== SE analytic / bootstrap CI coverage (antecedent-estimate) =="
run_ignored antecedent-estimate linear_adjustment_analytic_ci_coverage
run_ignored antecedent-estimate linear_adjustment_hc1_ci_coverage
run_ignored antecedent-estimate ipw_hajek_bootstrap_ci_coverage
run_ignored antecedent-estimate ipw_hajek_analytic_ci_coverage
run_ignored antecedent-estimate aipw_analytic_ci_coverage
run_ignored antecedent-estimate matching_homoskedastic_ci_coverage
run_ignored antecedent-estimate wald_iv_analytic_ci_coverage
run_ignored antecedent-estimate wald_iv_hc1_ci_coverage
run_ignored antecedent-estimate rd_sharp_analytic_ci_coverage

run_ignored antecedent-estimate bayesian_pulse_conjugate_nominal_90_coverage
run_ignored antecedent-estimate bayesian_sustained_single_step_conjugate_nominal_90_coverage
run_ignored antecedent-estimate bayesian_sustained_multi_step_conjugate_nominal_90_coverage
run_ignored antecedent-estimate bayesian_panel_hierarchical_nominal_90_coverage

echo "== 1.9 temporal / mixture interval coverage (antecedent) =="
run_ignored_test() {
  local filter="$1"
  echo "== antecedent: ${filter} =="
  cargo test --release -p antecedent --test v19_calibration "$filter" -- --ignored --exact --nocapture
}
run_ignored_test frequentist_dbn_pulse_shared_block_nominal_90_coverage
run_ignored_test frequentist_dbn_sustained_shared_block_nominal_90_coverage
run_ignored_test frequentist_dbn_multistep_sustained_shared_block_nominal_90_coverage
run_ignored_test frequentist_dbn_pulse_single_atom_baseline_nominal_90_coverage
run_ignored_test frequentist_dbn_pulse_ar1_rho05_n160_nominal_90_coverage
run_ignored_test frequentist_dbn_pulse_ar1_rho09_n400_nominal_90_coverage
run_ignored_test frequentist_dbn_pulse_ar1_rho05_n60_nominal_90_coverage
run_ignored_test frequentist_dbn_multistep_ar1_rho05_n160_nominal_90_coverage
run_ignored_test frequentist_dbn_multistep_ar1_rho09_n400_nominal_90_coverage
run_ignored_test frequentist_dbn_multistep_ar1_rho05_n60_nominal_90_coverage
run_ignored_test frequentist_temporal_cpdag_pulse_envelope_nominal_90_coverage
run_ignored_test frequentist_temporal_cpdag_sustained_envelope_nominal_90_coverage
run_ignored_test frequentist_temporal_cpdag_pulse_ar1_rho05_n160_nominal_90_coverage
run_ignored_test frequentist_temporal_cpdag_pulse_ar1_rho09_n400_nominal_90_coverage
run_ignored_test frequentist_temporal_cpdag_pulse_ar1_rho05_n60_nominal_90_coverage
run_ignored_test frequentist_temporal_pag_pulse_envelope_nominal_90_coverage
run_ignored_test bayesian_temporal_dag_pulse_staged_nominal_90_coverage
run_ignored_test bayesian_temporal_dag_multistep_sustained_nominal_90_coverage
run_ignored_test bayesian_temporal_dag_response_curve_pointwise_band_coverage
run_ignored_test bayesian_temporal_cpdag_pulse_class_prior_nominal_90_coverage
run_ignored_test bayesian_temporal_cpdag_sustained_class_prior_nominal_90_coverage
run_ignored_test class_prior_mixture_functional_nominal_90_coverage
run_ignored_test bayesian_temporal_pag_pulse_nominal_90_coverage
run_ignored_test bayesian_dbn_posterior_pulse_nominal_90_coverage
run_ignored_test bayesian_temporal_cpdag_mediation_envelope_nominal_90_coverage
run_ignored_test bayesian_temporal_cpdag_mediation_unconfounded_nominal_90_coverage

echo "== 1.9 shared circular-block length sensitivity (x0.5 / x1 / x2 of the rule) =="
run_ignored antecedent analysis::execute::block_length_tests::shared_block_length_sensitivity

echo "== 1.9 static graph-posterior mixture coverage (antecedent) =="
run_static_mixture_test() {
  local filter="$1"
  echo "== antecedent: ${filter} =="
  cargo test -p antecedent --test v19_static_mixture_calibration "$filter" -- --ignored --nocapture
}
run_static_mixture_test static_graph_posterior_frequentist_ate_joint_if_nominal_90_coverage
run_static_mixture_test static_graph_posterior_frequentist_cate_joint_if_nominal_90_coverage
run_static_mixture_test static_graph_posterior_bayesian_ate_bma_nominal_90_coverage
run_static_mixture_test static_graph_posterior_bayesian_cate_bma_nominal_90_coverage

echo "== 1.9 derivative-family interval coverage (antecedent) =="
run_ignored_derivative() {
  local filter="$1"
  echo "== antecedent: ${filter} =="
  cargo test --release -p antecedent --test v19_derivative_calibration "$filter" -- --ignored --nocapture --exact
}
run_ignored_derivative ade_frequentist_gaussian_treatment_nominal_90_coverage
run_ignored_derivative ade_bayesian_gaussian_treatment_nominal_90_coverage
run_ignored_derivative ade_skewed_heteroskedastic_treatment_probe
run_ignored_derivative point_derivative_frequentist_curvature_nominal_90_coverage
run_ignored_derivative point_derivative_bayesian_curvature_nominal_90_coverage
run_ignored_derivative semi_elasticity_log_treatment_frequentist_nominal_90_coverage
run_ignored_derivative semi_elasticity_log_treatment_bayesian_nominal_90_coverage
run_ignored_derivative semi_elasticity_log_outcome_bayesian_nominal_90_coverage
run_ignored_derivative elasticity_bayesian_nominal_90_coverage
run_ignored_derivative response_jacobian_bayesian_nominal_90_coverage
run_ignored_derivative directional_derivative_bayesian_nominal_90_coverage

echo "== 1.9 Bayesian temporal Pulse / Sustained under serial dependence (antecedent) =="
run_ignored_bayes_temporal() {
  local filter="$1"
  echo "== antecedent: ${filter} =="
  cargo test -p antecedent --test v19_bayesian_temporal "$filter" -- --ignored --nocapture
}
run_ignored_bayes_temporal bayesian_temporal_pulse_iid_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_pulse_ar1_rho05_n160_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_pulse_ar1_rho09_n400_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_pulse_ar1_rho05_n60_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_single_iid_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_single_ar1_rho05_n160_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_single_ar1_rho09_n400_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_single_ar1_rho05_n60_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_multi_iid_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_multi_ar1_rho05_n160_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_multi_ar1_rho09_n400_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_sustained_multi_ar1_rho05_n60_nominal_90_coverage
run_ignored_bayes_temporal bayesian_temporal_cpdag_class_prior_ar1_rho05_n160_nominal_90_coverage

echo "== 1.9 dependence-honest Frequentist TemporalDag SEs (R-1, R-2) =="
run_temporal_frequentist() {
  local filter="$1"
  echo "== antecedent: ${filter} =="
  cargo test -p antecedent --test v19_temporal_frequentist "$filter" -- --ignored --exact --nocapture
}
run_temporal_frequentist temporal_dag_pulse_iid_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_ar05_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_ar09_n400_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_ar05_n60_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_h2_iid_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_h2_ar05_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_h2_ar09_n400_nominal_90_coverage
run_temporal_frequentist temporal_dag_pulse_h2_ar05_n60_nominal_90_coverage
run_temporal_frequentist temporal_dag_sustained_iid_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_sustained_ar05_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_sustained_ar09_n400_nominal_90_coverage
run_temporal_frequentist temporal_dag_sustained_ar05_n60_nominal_90_coverage
run_temporal_frequentist temporal_dag_mediation_iid_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_mediation_ar05_n160_nominal_90_coverage
run_temporal_frequentist temporal_dag_mediation_ar09_n400_nominal_90_coverage
run_temporal_frequentist temporal_dag_mediation_ar05_n60_nominal_90_coverage
# Below the effective-sample floor: warning enforced, coverage recorded, not gated.
run_temporal_frequentist temporal_dag_pulse_ar09_n160_short_series_boundary
run_temporal_frequentist temporal_dag_mediation_ar09_n160_short_series_boundary
run_temporal_frequentist temporal_dag_pulse_ar09_n60_short_series_boundary
run_temporal_frequentist temporal_dag_mediation_ar09_n60_short_series_boundary

echo "== 1.9 static envelope / tier coverage (antecedent, release) =="
run_static_envelope() {
  local filter="$1"
  echo "== antecedent: ${filter} =="
  cargo test --release -p antecedent --test v19_static_envelope_calibration "$filter" \
    -- --ignored --nocapture --exact
}
run_static_envelope static_cpdag_ate_envelope_frequentist_nominal_90_coverage
run_static_envelope static_cpdag_ate_envelope_bayesian_nominal_90_coverage
run_static_envelope static_pag_ate_envelope_frequentist_nominal_90_coverage
run_static_envelope static_pag_ate_envelope_bayesian_nominal_90_coverage
run_static_envelope conditional_effect_dag_frequentist_nominal_90_coverage
run_static_envelope conditional_effect_dag_frequentist_small_subgroup_nominal_90_coverage
run_static_envelope conditional_effect_dag_bayesian_nominal_90_coverage
run_static_envelope conditional_effect_cpdag_frequentist_nominal_90_coverage
run_static_envelope conditional_effect_cpdag_bayesian_nominal_90_coverage
run_static_envelope conditional_effect_pag_frequentist_nominal_90_coverage
run_static_envelope conditional_effect_pag_bayesian_nominal_90_coverage
run_static_envelope codetermined_aipw_closure_nominal_90_coverage
run_static_envelope unknown_two_scenario_joint_band_nominal_95_coverage

echo "== Bayesian posterior calibration (antecedent-validate) =="
run_ignored antecedent-validate \
  bayesian_checks::tests::calibration_gate::sbc_conjugate_gaussian_ranks_are_uniform
run_ignored antecedent-validate \
  bayesian_checks::tests::calibration_gate::posterior_calibration_synthetic_scm_nominal_90_coverage

echo "== CI Type I / permutation uniformity (antecedent-stats) =="
run_ignored antecedent-stats robust_parcorr_calibration_gate
run_ignored antecedent-stats weighted_parcorr_calibration_gate
run_ignored antecedent-stats gsquared_calibration_gate
run_ignored antecedent-stats knn_dependence_calibration_gate
run_ignored antecedent-stats parcorr_perm_pvalue_uniformity_gate
run_ignored antecedent-stats knn_perm_pvalue_uniformity_gate
run_ignored antecedent-stats multivariate_block_calibration_gate
run_ignored antecedent-stats multivariate_block_shuffle_calibration_gate
run_ignored antecedent-stats gpdc_block_shuffle_autocorrelated_type_i_gate
run_ignored antecedent-stats knn_unconditional_block_shuffle_autocorrelated_type_i_gate

echo "== Discovery null FPR / power (antecedent-discovery) =="
run_ignored antecedent-discovery pc_null_fpr_near_alpha
run_ignored antecedent-discovery pcmci_null_fpr_near_alpha
run_ignored antecedent-discovery pcmci_planted_lag1_power

echo "== 0.5.0 response/observation/transport/interference =="
bash scripts/gate_response_calibration.sh

echo "gate_calibration: ok"
