#!/usr/bin/env python3
"""Generate docs/support-matrix.md from parity/support_*.toml.

Idempotent: re-running with no matrix changes must leave a clean git tree.
"""

from __future__ import annotations

import sys
import tomllib
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "support-matrix.md"
RUST_OUT = ROOT / "crates" / "antecedent" / "src" / "support_matrix_data.rs"


def load(rel: str) -> dict:
    return tomllib.loads((ROOT / rel).read_text())


def matches(rule: dict, cell: dict) -> bool:
    mapping = {
        "queries": "query",
        "graph_classes": "graph_class",
        "structures": "structure",
        "inferences": "inference",
        "validations": "validation",
    }
    for rule_key, cell_key in mapping.items():
        allowed = rule.get(rule_key)
        if allowed is not None and cell[cell_key] not in allowed:
            return False
    return True


def main() -> int:
    axes = load("parity/support_axes.toml")
    na_rules = load("parity/support_n_a.toml").get("n_a") or []
    closed_rules = load("parity/support_closed.toml").get("closed") or []
    cells = load("parity/support_licensed.toml").get("cell") or []
    queries = list(axes["queries"]) + list(axes.get("stage_queries") or [])
    graphs = list(axes["graph_classes"])
    structures = list(axes["structures"])
    inferences = list(axes["inferences"])
    validations = list(axes["validations"])

    def is_n_a(cell: dict) -> bool:
        return any(matches(rule, cell) for rule in na_rules)

    def is_closed(cell: dict) -> bool:
        return (not is_n_a(cell)) and any(matches(rule, cell) for rule in closed_rules)

    cartesian = 0
    n_a_count = 0
    closed_count = 0
    for q, g, s, inf, v in product(queries, graphs, structures, inferences, validations):
        cartesian += 1
        cell = {
            "query": q,
            "graph_class": g,
            "structure": s,
            "inference": inf,
            "validation": v,
        }
        if is_n_a(cell):
            n_a_count += 1
        elif is_closed(cell):
            closed_count += 1
    refused = cartesian - n_a_count - len(cells)
    default_refused = refused - closed_count

    def bullets(xs: list[str]) -> str:
        return "\n".join(f"- `{x}`" for x in xs)

    def rule_lines(rules: list[dict]) -> list[str]:
        lines = []
        for rule in rules:
            bits = []
            for key in ("queries", "graph_classes", "structures", "inferences", "validations"):
                if key in rule:
                    bits.append(f"{key} ∈ {{{', '.join(rule[key])}}}")
            lines.append(f"- {' ∧ '.join(bits)} — {rule['reason']}")
        return lines

    na_lines = rule_lines(na_rules)
    closed_lines = rule_lines(closed_rules)

    if cells:
        lic_rows = [
            "| query | graph | structure | inference | validation | evidence |",
            "|---|---|---|---|---|---|",
        ]
        for row in cells:
            ev = row.get("evidence_kind", "")
            fix = row.get("known_truth_fixture", "")
            ev_s = f"{ev}" + (f" (`{fix}`)" if fix else "")
            lic_rows.append(
                f"| `{row['query']}` | `{row['graph_class']}` | `{row['structure']}` | "
                f"`{row['inference']}` | `{row['validation']}` | {ev_s} |"
            )
        licensed_md = "\n".join(lic_rows)
    else:
        licensed_md = (
            "No licensed cells yet. Every remaining combination is **refused** "
            "until it runs on the staged path (`identify` → prepare → estimate) "
            "with recorded evidence."
        )

    text = f"""# Support matrix

Generated by `scripts/generate_support_matrix_docs.py` from
`parity/support_axes.toml`, `parity/support_n_a.toml`,
`parity/support_closed.toml`, and `parity/support_licensed.toml`.
Do not edit this page by hand.

This page is the public **license**. `docs/capabilities.md` is an inventory
of what exists in the codebase; it does not license a cell.
See [ADR 0020](../adr/0020-support-matrix-and-prepared-workflow.md).

| Status | Count |
|---|---|
| Cartesian product | {cartesian} |
| Licensed | {len(cells)} |
| n/a | {n_a_count} |
| Refused (enforced) | {closed_count} |
| Refused (default, not yet enforced) | {default_refused} |

A missing cell is refused, not unspecified. `analyze` is sugar over the
staged path; a combination that only works inside `analyze` cannot be
licensed.

## Axes

**Queries** (root `__all__`):

{bullets(list(axes["queries"]))}

**Stage queries** (not folded into `analyze`):

{bullets(list(axes.get("stage_queries") or []))}

**Graph classes** (`GraphClass`):

{bullets(graphs)}

**Structure source:** {", ".join(f"`{x}`" for x in structures)}.

**Inference:** {", ".join(f"`{x}`" for x in inferences)}.

**Validation:** {", ".join(f"`{x}`" for x in validations)}.

## n/a

{chr(10).join(na_lines) if na_lines else "_None._"}

## Enforced refusals

These default-refused cells now fail closed with id `refused`.
Other refused cells still run until licensed or closed.

{chr(10).join(closed_lines) if closed_lines else "_None._"}

## Licensed cells

{licensed_md}
"""
    OUT.write_text(text)
    RUST_OUT.write_text(render_rust(na_rules, closed_rules, cells))
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"Wrote {RUST_OUT.relative_to(ROOT)}")
    return 0


def rust_list(values: list[str] | None) -> str:
    if values is None:
        return "None"
    if not values:
        return "Some(&[])"
    inner = ", ".join(f'"{v}"' for v in values)
    return f"Some(&[{inner}])"


def rust_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_rules(rules: list[dict]) -> str:
    items = []
    for rule in rules:
        items.append(
            "    NaRule {\n"
            f"        queries: {rust_list(rule.get('queries'))},\n"
            f"        graph_classes: {rust_list(rule.get('graph_classes'))},\n"
            f"        structures: {rust_list(rule.get('structures'))},\n"
            f"        inferences: {rust_list(rule.get('inferences'))},\n"
            f"        validations: {rust_list(rule.get('validations'))},\n"
            f"        reason: \"{rust_escape(rule['reason'])}\",\n"
            "    }"
        )
    return ",\n".join(items) if items else ""


def render_rust(na_rules: list[dict], closed_rules: list[dict], cells: list[dict]) -> str:
    na_block = render_rules(na_rules)
    closed_block = render_rules(closed_rules)
    lic_items = []
    for row in cells:
        lic_items.append(
            "    LicensedCell {\n"
            f"        query: \"{rust_escape(row['query'])}\",\n"
            f"        graph_class: \"{rust_escape(row['graph_class'])}\",\n"
            f"        structure: \"{rust_escape(row['structure'])}\",\n"
            f"        inference: \"{rust_escape(row['inference'])}\",\n"
            f"        validation: \"{rust_escape(row['validation'])}\",\n"
            "    }"
        )
    lic_block = ",\n".join(lic_items) if lic_items else ""
    return f"""//! Generated from `parity/support_*.toml`. Do not edit.

#![allow(missing_docs)]

#[derive(Clone, Copy, Debug)]
pub struct NaRule {{
    pub queries: Option<&'static [&'static str]>,
    pub graph_classes: Option<&'static [&'static str]>,
    pub structures: Option<&'static [&'static str]>,
    pub inferences: Option<&'static [&'static str]>,
    pub validations: Option<&'static [&'static str]>,
    pub reason: &'static str,
}}

#[derive(Clone, Copy, Debug)]
pub struct LicensedCell {{
    pub query: &'static str,
    pub graph_class: &'static str,
    pub structure: &'static str,
    pub inference: &'static str,
    pub validation: &'static str,
}}

pub static NA_RULES: &[NaRule] = &[
{na_block}
];

pub static CLOSED_RULES: &[NaRule] = &[
{closed_block}
];

pub static LICENSED: &[LicensedCell] = &[
{lic_block}
];
"""


if __name__ == "__main__":
    sys.exit(main())
