#!/usr/bin/env python3
"""Generate docs/support-matrix.md from parity/support_*.toml.

Idempotent: re-running with no matrix changes must leave a clean git tree.
"""

from __future__ import annotations

import sys
import tomllib
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "support-matrix.md"


def load(rel: str) -> dict:
    return tomllib.loads((ROOT / rel).read_text())


def matches(rule: dict, cell: dict) -> bool:
    mapping = {
        "queries": "query",
        "graph_classes": "graph_class",
        "structures": "structure",
        "inferences": "inference",
        "validations": "validation",
    }
    for rule_key, cell_key in mapping.items():
        allowed = rule.get(rule_key)
        if allowed is not None and cell[cell_key] not in allowed:
            return False
    return True


def main() -> int:
    axes = load("parity/support_axes.toml")
    na_rules = load("parity/support_n_a.toml").get("n_a") or []
    cells = load("parity/support_licensed.toml").get("cell") or []
    queries = list(axes["queries"]) + list(axes.get("stage_queries") or [])
    graphs = list(axes["graph_classes"])
    structures = list(axes["structures"])
    inferences = list(axes["inferences"])
    validations = list(axes["validations"])

    def is_n_a(cell: dict) -> bool:
        return any(matches(rule, cell) for rule in na_rules)

    cartesian = 0
    n_a_count = 0
    for q, g, s, inf, v in product(queries, graphs, structures, inferences, validations):
        cartesian += 1
        if is_n_a(
            {
                "query": q,
                "graph_class": g,
                "structure": s,
                "inference": inf,
                "validation": v,
            }
        ):
            n_a_count += 1
    refused = cartesian - n_a_count - len(cells)

    def bullets(xs: list[str]) -> str:
        return "\n".join(f"- `{x}`" for x in xs)

    na_lines = []
    for rule in na_rules:
        bits = []
        for key in ("queries", "graph_classes", "structures", "inferences", "validations"):
            if key in rule:
                bits.append(f"{key} ∈ {{{', '.join(rule[key])}}}")
        na_lines.append(f"- {' ∧ '.join(bits)} — {rule['reason']}")

    if cells:
        lic_rows = [
            "| query | graph | structure | inference | validation | evidence |",
            "|---|---|---|---|---|---|",
        ]
        for row in cells:
            ev = row.get("evidence_kind", "")
            fix = row.get("known_truth_fixture", "")
            ev_s = f"{ev}" + (f" (`{fix}`)" if fix else "")
            lic_rows.append(
                f"| `{row['query']}` | `{row['graph_class']}` | `{row['structure']}` | "
                f"`{row['inference']}` | `{row['validation']}` | {ev_s} |"
            )
        licensed_md = "\n".join(lic_rows)
    else:
        licensed_md = (
            "No licensed cells yet. Every remaining combination is **refused** "
            "until it runs on the staged path (`identify` → prepare → estimate) "
            "with recorded evidence."
        )

    text = f"""# Support matrix

Generated by `scripts/generate_support_matrix_docs.py` from
`parity/support_axes.toml`, `parity/support_n_a.toml`, and
`parity/support_licensed.toml`. Do not edit this page by hand.

This page is the public **license**. `docs/capabilities.md` is an inventory
of what exists in the codebase; it does not license a cell.
See [ADR 0020](../adr/0020-support-matrix-and-prepared-workflow.md).

| Status | Count |
|---|---|
| Cartesian product | {cartesian} |
| Licensed | {len(cells)} |
| n/a | {n_a_count} |
| Refused (default) | {refused} |

A missing cell is refused, not unspecified. `analyze` is sugar over the
staged path; a combination that only works inside `analyze` cannot be
licensed.

## Axes

**Queries** (root `__all__`):

{bullets(list(axes["queries"]))}

**Stage queries** (not folded into `analyze`):

{bullets(list(axes.get("stage_queries") or []))}

**Graph classes** (`GraphClass`):

{bullets(graphs)}

**Structure source:** {", ".join(f"`{x}`" for x in structures)}.

**Inference:** {", ".join(f"`{x}`" for x in inferences)}.

**Validation:** {", ".join(f"`{x}`" for x in validations)}.

## n/a

{chr(10).join(na_lines) if na_lines else "_None._"}

## Licensed cells

{licensed_md}
"""
    OUT.write_text(text)
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
