#!/usr/bin/env python3
"""Generate the licensed interval-calibration debt by distinct coordinate.

The checked-in inventory is deliberately separate from the Bayesian parity
report. Validation variants share a coordinate but retain their cell count.
"""

from __future__ import annotations

import argparse
import tomllib
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "parity/support_licensed.toml"
OUTPUT = ROOT / "parity/calibration_backlog.md"


def reviewed_ceiling() -> int:
    """Use the existing reason-code ratchet as the single reviewed ceiling."""
    codes = tomllib.loads((ROOT / "parity/reason_codes.toml").read_text())["code"]
    return next(
        int(code["max_uses"])
        for code in codes if code["id"] == "estimator_grid_not_measured"
    )


def render() -> tuple[str, int]:
    cells = tomllib.loads(SOURCE.read_text())["cell"]
    gaps = [
        cell for cell in cells
        if cell.get("calibration_reason") == "estimator_grid_not_measured"
    ]
    counts: Counter[tuple[str, str, str, str]] = Counter(
        (cell["query"], cell["graph_class"], cell["structure"], cell["inference"])
        for cell in gaps
    )
    lines = [
        "# Licensed interval-calibration backlog",
        "",
        "Generated by `scripts/generate_calibration_backlog.py` from the support registry.",
        "Each coordinate groups validation variants; the cell column counts those variants.",
        "A missing measurement is visible here and does not imply calibrated coverage.",
        "",
        f"**{len(gaps)} unmeasured cells across {len(counts)} distinct coordinates.**",
        "",
        "| Query | Graph | Structure | Inference | Cells |",
        "| --- | --- | --- | --- | ---: |",
    ]
    lines.extend(
        f"| {query} | {graph} | {structure} | {inference} | {count} |"
        for (query, graph, structure, inference), count in sorted(counts.items())
    )
    lines.append("")
    return "\n".join(lines), len(gaps)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text, count = render()
    ceiling = reviewed_ceiling()
    if count > ceiling:
        parser.error(
            f"{count} unmeasured cells exceed reviewed ceiling {ceiling}"
        )
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            parser.error(f"{OUTPUT.relative_to(ROOT)} is stale")
    else:
        OUTPUT.write_text(text)
    print(f"Calibration backlog: {count} cells")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
