#!/usr/bin/env python3
"""Generate docs/conformance/*.md from conformance/*/ fixtures.

Idempotent: re-running with no fixture changes must leave a clean git tree.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONF = ROOT / "conformance"
OUT = ROOT / "docs" / "conformance"


def fixture_dirs() -> list[Path]:
    dirs: list[Path] = []
    for suite in sorted(p for p in CONF.iterdir() if p.is_dir()):
        for fix in sorted(p for p in suite.iterdir() if p.is_dir()):
            if (fix / "expected.json").exists() or (fix / "README.md").exists():
                dirs.append(fix)
    return dirs


def summarize_expected(path: Path) -> str:
    if not path.exists():
        return "_No `expected.json`._"
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        return f"_Invalid JSON: {e}_"
    if isinstance(data, dict):
        keys = ", ".join(sorted(data.keys())[:24])
        extra = "…" if len(data) > 24 else ""
        return f"Top-level keys: `{keys}{extra}` ({len(data)} fields)."
    if isinstance(data, list):
        return f"JSON array with {len(data)} elements."
    return f"JSON `{type(data).__name__}`."


def render_fixture(fix: Path) -> str:
    rel = fix.relative_to(CONF)
    readme = fix / "README.md"
    body = readme.read_text().strip() if readme.exists() else f"# {fix.name}\n"
    # Drop leading H1 from README if present; we emit our own.
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        title = lines[0][2:].strip()
        rest = "\n".join(lines[1:]).strip()
    else:
        title = fix.name.replace("_", " ")
        rest = body
    parts = [
        f"# {title}",
        "",
        f"**Suite path:** `conformance/{rel.as_posix()}`",
        "",
    ]
    if rest:
        parts.extend([rest, ""])
    parts.extend(
        [
            "## Expected summary",
            "",
            summarize_expected(fix / "expected.json"),
            "",
        ]
    )
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    # Remove previously generated pages (keep directory).
    for old in OUT.glob("*.md"):
        if old.name != "README.md":
            old.unlink()

    index_rows: list[str] = []
    for fix in fixture_dirs():
        rel = fix.relative_to(CONF)
        slug = rel.as_posix().replace("/", "__")
        page = OUT / f"{slug}.md"
        page.write_text(render_fixture(fix))
        index_rows.append(f"- [`{rel.as_posix()}`]({slug}.md)")

    index = "\n".join(
        [
            "# Conformance fixtures",
            "",
            "Generated by `scripts/generate_conformance_docs.py` from",
            "`conformance/`. Do not edit these pages by hand; re-run the script.",
            "",
            *index_rows,
            "",
        ]
    )
    (OUT / "README.md").write_text(index)
    print(f"Wrote {len(index_rows)} fixture pages under {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
