#!/usr/bin/env python3
"""Short-series thresholds: derived from the measurement's per-replicate records, rendered into the docs.

The measurement (`crates/antecedent/tests/v19_short_series_measurement.rs`, an ignored
provenance run, not a gate) writes one CSV row per replicate when
`ANTECEDENT_SHORT_SERIES_CSV=<path>` is set. This script owns the rule that turns those
rows into a per-family threshold, the registry of the latest result
(`parity/short_series_thresholds.toml`) and the two tables in
`docs/short-series-thresholds.md`, so neither table is typed by hand:

    # derive from a sweep and its independent-seed replication, rewrite registry + docs
    python3 scripts/short_series_thresholds.py write --sweep sweep.csv --replication rep.csv
    # the gate: docs tables equal the registry; registry equals temporal_block.rs
    python3 scripts/short_series_thresholds.py check
    # what a CSV implies, without writing anything
    python3 scripts/short_series_thresholds.py derive sweep.csv

The rule (the page states it): a threshold is the smallest multiple of 5 at which every
cell whose nominal-0.90 coverage is under FAILURE_LINE (0.855, the lower edge of the
400-replicate gate band) warns on at least WARN_SHARE (90%) of its replicates. A replicate
warns when its score effective rows are under the threshold, so the rule is evaluated
from the CSV's `effective_rows` column for any candidate. The registry threshold is the
larger of the sweep's and the replication's, and it may be pinned above that (never
below) with a stated reason.

SPDX-License-Identifier: MIT OR Apache-2.0
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "parity" / "short_series_thresholds.toml"
DOC = ROOT / "docs" / "short-series-thresholds.md"
TEMPORAL_BLOCK = ROOT / "crates" / "antecedent-estimate" / "src" / "temporal_block.rs"

FAILURE_LINE = 0.855
WARN_SHARE = 0.90
STEP = 5

# Rust `min_effective_rows` arm name for each registry family.
RUST_ARMS = {
    "single-window adjustment": "SingleWindow",
    "temporal mediation": "Mediation",
    "multi-step sequential": "Sequential",
    "multi-atom mixture": "Mixture",
}
# CSV `family` column value for each registry family.
CSV_FAMILIES = {
    "single-window adjustment": "single-window",
    "temporal mediation": "mediation",
    "multi-step sequential": "sequential",
    "multi-atom mixture": "mixture",
}

BEGIN = "<!-- short-series-table: {name} begin (generated by scripts/short_series_thresholds.py) -->"
END = "<!-- short-series-table: {name} end -->"


def derive(csv_path: Path) -> dict[str, int]:
    """Per registry family: the smallest multiple of 5 meeting the rule on this sweep."""
    cells: dict[tuple, list[dict]] = defaultdict(list)
    with csv_path.open(newline="") as handle:
        for row in csv.DictReader(handle):
            cells[(row["family"], row["design"], row["rho"], row["n"])].append(row)
    out: dict[str, int] = {}
    for family, csv_family in CSV_FAMILIES.items():
        failing: list[list[float]] = []
        for (fam, *_), rows in cells.items():
            if fam != csv_family:
                continue
            width = len(rows[0]["covered"].split("/"))
            below = any(
                sum(int(r["covered"].split("/")[i]) for r in rows) / len(rows) < FAILURE_LINE
                for i in range(width)
            )
            if below:
                failing.append([float(r["effective_rows"]) for r in rows])
        if not failing:
            raise SystemExit(f"{csv_path}: no {csv_family} cell covers under {FAILURE_LINE}")
        top = max(max(eff) for eff in failing)
        threshold = STEP
        while not all(
            sum(1 for e in eff if e < threshold) / len(eff) >= WARN_SHARE for eff in failing
        ):
            threshold += STEP
            if threshold > top + 2 * STEP:
                raise SystemExit(f"{csv_family}: no threshold meets the rule on {csv_path}")
        out[family] = threshold
    return out


def load(path: Path = REGISTRY) -> list[dict]:
    return tomllib.loads(path.read_text())["family"]


def problems_in(rows: list[dict]) -> list[str]:
    problems = []
    if [r["name"] for r in rows] != list(RUST_ARMS):
        problems.append(f"registry families must be exactly {list(RUST_ARMS)} in order")
    for r in rows:
        derived = max(int(r["sweep"]), int(r["replication"]))
        if int(r["threshold"]) < derived:
            problems.append(
                f"{r['name']}: threshold {r['threshold']} is below the measured "
                f"max(sweep {r['sweep']}, replication {r['replication']}) = {derived}"
            )
        if int(r["threshold"]) > derived and not str(r.get("pinned_reason", "")).strip():
            problems.append(
                f"{r['name']}: threshold {r['threshold']} is above the measured {derived} "
                "and states no pinned_reason"
            )
        if int(r["threshold"]) % STEP:
            problems.append(f"{r['name']}: threshold {r['threshold']} is not a multiple of {STEP}")
    return problems


def render(name: str, rows: list[dict]) -> str:
    if name == "thresholds":
        lines = ["| family | SE path | threshold |", "|---|---|---|"]
        lines += [f"| {r['name']} | {r['se_path']} | {r['threshold']} |" for r in rows]
    else:
        lines = ["| family | sweep | replication | threshold |", "|---|---|---|---|"]
        lines += [
            f"| {r['name']} | {r['sweep']} | {r['replication']} | {r['threshold']} |" for r in rows
        ]
    return "\n".join(lines)


def block(name: str, rows: list[dict]) -> str:
    return f"{BEGIN.format(name=name)}\n{render(name, rows)}\n{END.format(name=name)}"


def substitute(text: str, rows: list[dict]) -> str:
    for name in ("thresholds", "measured"):
        pattern = re.compile(
            re.escape(BEGIN.format(name=name)) + r".*?" + re.escape(END.format(name=name)), re.S
        )
        if not pattern.search(text):
            raise SystemExit(f"{DOC.name}: no generated `{name}` table markers")
        text = pattern.sub(lambda _: block(name, rows), text, count=1)
    return text


def rust_thresholds() -> dict[str, int]:
    return {
        name: int(m.group(2))
        for m in re.finditer(
            r"((?:Self::\w+\s*\|\s*)*Self::\w+)\s*=>\s*(\d+)\.0", TEMPORAL_BLOCK.read_text()
        )
        for name in re.findall(r"Self::(\w+)", m.group(1))
    }


def check() -> list[str]:
    rows = load()
    problems = problems_in(rows)
    text = DOC.read_text()
    if substitute(text, rows) != text:
        problems.append(
            f"{DOC.relative_to(ROOT)}: a table differs from parity/short_series_thresholds.toml; "
            "regenerate with `python3 scripts/short_series_thresholds.py write` (docs only) "
            "or from a measurement (`write --sweep ... --replication ...`)"
        )
    rust = rust_thresholds()
    for r in rows:
        arm = RUST_ARMS[r["name"]]
        if rust.get(arm) != int(r["threshold"]):
            problems.append(
                f"{r['name']}: registry threshold {r['threshold']} but temporal_block.rs "
                f"has {rust.get(arm)} for {arm}"
            )
    return problems


def write_registry(rows: list[dict]) -> None:
    lines = [
        "# Latest short-series threshold measurement, per family.",
        "#",
        "# `sweep` and `replication` are the smallest multiples of 5 the rule in",
        "# scripts/short_series_thresholds.py yields on the measurement sweep and on its",
        "# independent-seed replication (ANTECEDENT_SHORT_SERIES_SEED_OFFSET=5000, 1000",
        "# replicates); `threshold` is the larger, or a stated pin above it. Rows are written",
        "# by `python3 scripts/short_series_thresholds.py write`; the docs tables are",
        "# generated from them and gate_docs_support_matrix.sh ties `threshold` to",
        "# min_effective_rows in crates/antecedent-estimate/src/temporal_block.rs.",
        "",
    ]
    for r in rows:
        lines += [
            "[[family]]",
            f'name = "{r["name"]}"',
            f'se_path = "{r["se_path"]}"',
            f"sweep = {int(r['sweep'])}",
            f"replication = {int(r['replication'])}",
            f"threshold = {int(r['threshold'])}",
        ]
        if str(r.get("pinned_reason", "")).strip():
            escaped = r["pinned_reason"].replace('"', '\\"')
            lines.append(f'pinned_reason = "{escaped}"')
        lines.append("")
    REGISTRY.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("check", help="docs tables and temporal_block.rs agree with the registry")
    d = sub.add_parser("derive", help="print the thresholds a measurement CSV implies")
    d.add_argument("csv", type=Path)
    w = sub.add_parser("write", help="rewrite the registry (from CSVs, if given) and the docs tables")
    w.add_argument("--sweep", type=Path)
    w.add_argument("--replication", type=Path)
    args = parser.parse_args()
    if args.command == "derive":
        for family, threshold in derive(args.csv).items():
            print(f"{family}: {threshold}")
        return 0
    if args.command == "check":
        found = check()
        for problem in found:
            print(f"FAIL: {problem}")
        if not found:
            print("short-series thresholds: registry, docs tables and temporal_block.rs agree")
        return 1 if found else 0
    rows = load()
    if bool(args.sweep) != bool(args.replication):
        raise SystemExit("--sweep and --replication go together")
    if args.sweep:
        sweep, replication = derive(args.sweep), derive(args.replication)
        for r in rows:
            r["sweep"], r["replication"] = sweep[r["name"]], replication[r["name"]]
            measured = max(sweep[r["name"]], replication[r["name"]])
            # A pin above the measurement stays; a measurement above the pin raises it.
            r["threshold"] = max(int(r["threshold"]), measured) if r.get("pinned_reason") else measured
        found = problems_in(rows)
        if found:
            raise SystemExit("\n".join(found))
        write_registry(rows)
    DOC.write_text(substitute(DOC.read_text(), rows))
    print("wrote", REGISTRY.relative_to(ROOT), "and", DOC.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
