"""Package type stub for ``antecedent``.

Day-1: ``analyze``, queries, ``Dag``/graphs, ``identify``, ``fit_gcm``,
``Identifier``/``Estimator``, inference modes, ``AnalysisResult``.
Stage depth: ``antecedent.discovery``, ``antecedent.gcm``, ``antecedent.graph``, etc.
``AteAnalysisResult`` is private to ``antecedent._native``.
"""

from __future__ import annotations

from . import (
    attribution,
    counterfactual,
    data,
    design,
    discovery,
    estimation,
    extensibility,
    gcm,
    graph,
    inference,
    model,
    population,
    query,
    state,
    validation,
)
from ._analyze_handlers import analyze
from ._native import (
    Admg,
    AnomalyScores,
    ArrowLoadInfo,
    CancellationToken,
    CausalAttributionError,
    CausalCancelledError,
    CausalCompileError,
    CausalCounterfactualError,
    CausalDataError,
    CausalDesignError,
    CausalDiscoveryError,
    CausalError,
    CausalEstimateError,
    CausalGraphError,
    CausalIdentifyError,
    CausalModelError,
    CausalResourceError,
    CausalReviewError,
    CausalSerializationError,
    CausalState,
    CausalStateError,
    CausalUnsupportedError,
    CausalValidateError,
    ChangeAttributionResult,
    Contribution,
    Cpdag,
    Dag,
    DecisionEvaluation,
    DesignRanking,
    DiscoveredLink,
    FeatureRelevance,
    FittedGcm,
    GcmIteResult,
    GcmSampleResult,
    GraphEdge,
    GraphPosterior,
    MechanismChangeDetection,
    MediationEffectsSummary,
    Pag,
    PcmciDiscoveryResult,
    PosteriorArtifact,
    PredictSummary,
    RpcmciDiscoverySummary,
    TemporalCpdag,
    TemporalDag,
    TemporalPag,
    anomaly_attribution,
    attribute_distribution_change,
    attribute_distribution_change_robust,
    attribute_feature_relevance,
    attribute_path_specific,
    attribute_paths,
    attribute_structure_change,
    attribute_unit_change,
    counterfactual_ite,
    dag_from_dot,
    dag_from_gml,
    dag_from_json,
    dag_from_networkx_adjacency,
    dag_from_networkx_node_link,
    dag_to_dot,
    dag_to_gml,
    dag_to_json,
    dag_to_networkx_adjacency,
    dag_to_networkx_node_link,
    decode_model_bundle,
    decode_posterior_artifact,
    encode_model_bundle,
    encode_posterior_artifact,
    fit_gcm,
    load_float64_arrow_c_columns,
    load_float64_columns,
    mechanism_change_detection,
    mediation_effects_summary,
    predict_intervened_summary,
    rank_designs,
    rank_root_causes,
    sample_do,
    sample_interventional_distribution,
)
from .accepted_graph import AcceptedGraph
from .data import EventFrame, MultiEnvFrame, PanelFrame, event, multi_env, panel
from .design import evaluate_decision
from .discovery import (
    FCI,
    GES,
    LPCMCI,
    NOTEARS,
    PC,
    PCMCI,
    RFCI,
    RPCMCI,
    CiScreenedPosterior,
    DbnPosterior,
    ExactDagPosterior,
    JPCMCIPlus,
    LiNGAM,
    OrderMcmc,
    PCMCIPlus,
    StructureMcmc,
    discover_ci_screened_posterior,
    discover_dbn_posterior,
    discover_exact_dag_posterior,
    discover_fci,
    discover_ges,
    discover_jpcmci_plus,
    discover_lingam,
    discover_lpcmci,
    discover_notears,
    discover_order_mcmc,
    discover_pc,
    discover_pcmci,
    discover_pcmci_plus,
    discover_rfci,
    discover_rpcmci,
    discover_structure_mcmc,
    two_regime_half_split,
)
from .estimation import (
    AnalysisResult,
    ConflictSummaryView,
    EffectEnvelope,
    IdentifyResult,
    PredictiveCheckReport,
    PreparedAnalysis,
    PriorSensitivityReport,
    analyze_many,
    identify,
)
from .gcm import (
    anomaly_attribution_discovered,
    attribute_distribution_change_discovered,
    attribute_paths_discovered,
    fit_gcm_discovered,
)
from .ids import Estimator, Identifier, Latency, Refute
from .inference import Bayesian, Frequentist
from .population import (
    PopulationRegistry,
    target_all,
    target_custom_distribution,
    target_named,
    target_rows,
    target_treated,
    target_untreated,
)
from .prior_bank import (
    POPULATION_TAG_KEY,
    CompatibilityReport,
    ComposedPrior,
    ConflictPolicy,
    DesignVariable,
    EstimandFingerprint,
    ExternalPriorSourceSpec,
    ExternalPriorWeight,
    PriorCatalog,
    PriorMapping,
    PriorSource,
    PriorSourceMeta,
    TransportPolicy,
    compose_external_priors,
    populations_from_prior_sources,
)
from .query import (
    AverageEffect,
    ConditionalEffect,
    Counterfactual,
    InterventionalDistribution,
    MediationEffect,
    PathSpecificEffect,
    PulseEffect,
    SustainedEffect,
    TemporalMediationEffect,
)
from .validation import (
    validate_environment_holdout,
    validate_pcmci_alpha_sensitivity,
    validate_pcmci_block_bootstrap,
    validate_pcmci_ci_sensitivity,
    validate_pcmci_false_positive,
    validate_pcmci_lag_sensitivity,
    validate_pcmci_plus_orientation,
    validate_regime_stability,
    validate_synthetic_null_calibration,
)

__version__: str

__all__: list[str]
