//! Coverage of Bayesian temporal Pulse / Sustained credible intervals (R-9).
//!
//! Every replicate runs the staged `Study` path. The treatment and the outcome
//! residual are independent stationary processes of one noise family
//! ([`Noise`]): AR(1) (`common::calibration::ar1_noise`), AR(2)(0.3, 0.5), an
//! ARMA(1,1)(0.5, 0.4) and an MA(2)(0.6, 0.4) robustness design. The treatment's
//! persistence is latent (the temporal identifier certifies no autoregressive
//! treatment edge), and the residual autocorrelation is latent too, so every DGP
//! sits inside the stated identification assumptions. With a persistent
//! treatment the score `x̃_t e_t` inherits the residual autocorrelation — the
//! case an iid Normal–Inverse-Gamma likelihood understates. The iid-residual
//! regime keeps a persistent treatment, so it checks that the dependence
//! correction does not over-widen when the iid likelihood is right.
//!
//! Ignored tests run via `scripts/gate_calibration.sh`.
//!
//! SPDX-License-Identifier: MIT OR Apache-2.0

#![allow(clippy::too_many_lines)]

mod common;

use antecedent::{BayesianConfig, ClassPrior, InferenceMode, RefuteSuite, Study, StudyResult};
use antecedent_core::{
    CausalQuery, ExecutionContext, Lag, MediationContrast, MediationQuery, TemporalEffectQuery,
    TemporalPolicy, VariableId,
};
use antecedent_data::TimeSeriesData;
use antecedent_graph::{TemporalCpdag, TemporalDag, ensure_lagged};
use common::calibration::{
    CoverageTally, REPORTED_LEVEL, RecordKey, ar1_noise, grid_n, map_replicates, n_sim,
    quantile_interval,
};
use common::calibration_bind::bind_all;

/// Effect of `x_{t-1}` on `y_t`.
const BETA1: f64 = 0.8;
/// Effect of `x_{t-2}` on `y_t` in the multi-step DGP (nonzero second lag).
const BETA2: f64 = 0.4;
const DRAWS: usize = 400;
const LEVEL: f64 = 0.9;
/// Treatment persistence used when the outcome residual is iid.
const IID_TREATMENT_RHO: f64 = 0.5;

/// Noise family of the treatment and the outcome residual.
#[derive(Clone, Copy, Debug, PartialEq)]
enum Noise {
    /// iid residual; the treatment stays AR(1) at [`IID_TREATMENT_RHO`].
    Iid,
    /// AR(1) treatment and residual at this coefficient.
    Ar1(f64),
    /// AR(2)(0.3, 0.5) treatment and residual: dominant root 0.87, so the
    /// autocorrelation decays far more slowly than an AR(1) fitted to its first lag.
    Ar2,
    /// ARMA(1,1)(φ 0.5, θ 0.4) treatment and residual: not in the AR(q) family the
    /// tempering factor fits.
    Arma11,
    /// MA(2)(0.6, 0.4) treatment and residual: finite memory, no AR representation
    /// of finite order.
    Ma2,
}

impl Noise {
    /// `(φ, θ)` of the ARMA families generated by [`arma_noise`].
    const fn arma(self) -> Option<(&'static [f64], &'static [f64])> {
        match self {
            Self::Ar2 => Some((&[0.3, 0.5], &[])),
            Self::Arma11 => Some((&[0.5], &[0.4])),
            Self::Ma2 => Some((&[], &[0.6, 0.4])),
            Self::Iid | Self::Ar1(_) => None,
        }
    }

    fn label(self) -> String {
        match self {
            Self::Iid => format!("iid residual (treatment rho {IID_TREATMENT_RHO})"),
            Self::Ar1(rho) => format!("AR(1) rho={rho}"),
            Self::Ar2 => "AR(2)(0.3, 0.5)".to_string(),
            Self::Arma11 => "ARMA(1,1)(0.5, 0.4)".to_string(),
            Self::Ma2 => "MA(2)(0.6, 0.4)".to_string(),
        }
    }
}

/// Noise regime: family and series length.
#[derive(Clone, Copy, Debug)]
struct Regime {
    noise: Noise,
    n: usize,
    seed: u64,
}

impl Regime {
    const IID: Self = Self { noise: Noise::Iid, n: 160, seed: 1_000_000 };
    const RHO05_N160: Self = Self { noise: Noise::Ar1(0.5), n: 160, seed: 2_000_000 };
    const RHO09_N400: Self = Self { noise: Noise::Ar1(0.9), n: 400, seed: 3_000_000 };
    const RHO05_N60: Self = Self { noise: Noise::Ar1(0.5), n: 60, seed: 4_000_000 };
    const AR2_N400: Self = Self { noise: Noise::Ar2, n: 400, seed: 5_000_000 };
    const AR2_N160: Self = Self { noise: Noise::Ar2, n: 160, seed: 6_000_000 };
    const AR2_N60: Self = Self { noise: Noise::Ar2, n: 60, seed: 7_000_000 };
    const AR2_N100: Self = Self { noise: Noise::Ar2, n: 100, seed: 8_000_000 };
    const ARMA11_N60: Self = Self { noise: Noise::Arma11, n: 60, seed: 9_000_000 };
    const ARMA11_N100: Self = Self { noise: Noise::Arma11, n: 100, seed: 10_000_000 };
    const ARMA11_N160: Self = Self { noise: Noise::Arma11, n: 160, seed: 11_000_000 };
    const ARMA11_N400: Self = Self { noise: Noise::Arma11, n: 400, seed: 12_000_000 };
    const MA2_N60: Self = Self { noise: Noise::Ma2, n: 60, seed: 13_000_000 };
    const MA2_N160: Self = Self { noise: Noise::Ma2, n: 160, seed: 14_000_000 };

    fn label(self) -> String {
        format!("{} n={}", self.noise.label(), self.n)
    }

    /// The regime at this run's sample-size grid point (`n` is the base point).
    fn at_grid(self) -> Self {
        Self { n: grid_n(self.n), ..self }
    }

    /// Stream seed for `rep`. The harness generator uses `seed | 1`, so streams
    /// must differ above bit 0: offsets are odd and ten apart per replicate.
    fn stream(self, rep: u64, k: u64) -> u64 {
        self.seed + 10 * rep + 2 * k + 1
    }

    /// Treatment series with marginal SD `sd`.
    fn treatment(self, sd: f64, seed: u64) -> Vec<f64> {
        match self.noise {
            Noise::Iid => ar1_noise(self.n, IID_TREATMENT_RHO, sd, seed),
            Noise::Ar1(rho) => ar1_noise(self.n, rho, sd, seed),
            family => {
                let (phi, theta) = family.arma().unwrap();
                arma_noise(self.n, phi, theta, sd, seed)
            }
        }
    }

    /// Residual (or innovation) series with marginal SD `sd`.
    fn residual(self, sd: f64, seed: u64) -> Vec<f64> {
        match self.noise {
            Noise::Iid => ar1_noise(self.n, 0.0, sd, seed),
            Noise::Ar1(rho) => ar1_noise(self.n, rho, sd, seed),
            family => {
                let (phi, theta) = family.arma().unwrap();
                arma_noise(self.n, phi, theta, sd, seed)
            }
        }
    }
}

/// Stationary ARMA(φ, θ) noise with marginal SD `sd` (500-step burn-in): the
/// unit-innovation process is scaled by `1 / sqrt(Σ ψ_k²)` of its MA(∞) weights.
fn arma_noise(n: usize, phi: &[f64], theta: &[f64], sd: f64, seed: u64) -> Vec<f64> {
    let mut ma_inf = vec![1.0];
    for k in 1..2_000 {
        let mut v = theta.get(k - 1).copied().unwrap_or(0.0);
        for (j, f) in phi.iter().enumerate() {
            if k > j {
                v += f * ma_inf[k - 1 - j];
            }
        }
        ma_inf.push(v);
    }
    let scale = sd / ma_inf.iter().map(|w| w * w).sum::<f64>().sqrt();
    let mut z = common::calibration::gaussian(seed);
    let burn = 500;
    let mut innovations = Vec::with_capacity(n + burn);
    let mut series: Vec<f64> = Vec::with_capacity(n + burn);
    for t in 0..n + burn {
        let innovation = z();
        let mut next = innovation;
        for (j, f) in phi.iter().enumerate() {
            if t > j {
                next += f * series[t - 1 - j];
            }
        }
        for (j, g) in theta.iter().enumerate() {
            if t > j {
                next += g * innovations[t - 1 - j];
            }
        }
        innovations.push(innovation);
        series.push(next);
    }
    series[burn..].iter().map(|v| scale * v).collect()
}

/// `y_t = 0.8 x_{t-1} + beta2 x_{t-2} + e_t`, `x` and `e` independent draws of the
/// regime's noise family.
fn series_xy(regime: Regime, rep: u64, beta2: f64) -> TimeSeriesData {
    let x = regime.treatment(0.5, regime.stream(rep, 0));
    let e = regime.residual(0.35, regime.stream(rep, 1));
    let mut y = vec![0.0; regime.n];
    for t in 2..regime.n {
        y[t] = BETA1 * x[t - 1] + beta2 * x[t - 2] + e[t];
    }
    TimeSeriesData::from_f64_columns([("x", x.as_slice()), ("y", y.as_slice())], 1).unwrap()
}

/// `x_{t-1} → y_t` (Pulse / single-step Sustained DGP has `beta2 = 0`).
fn lag1_dag() -> TemporalDag {
    let mut g = TemporalDag::empty();
    let x1 = ensure_lagged(&mut g, VariableId::from_raw(0), Lag::from_raw(1)).unwrap();
    let y0 = ensure_lagged(&mut g, VariableId::from_raw(1), Lag::CONTEMPORANEOUS).unwrap();
    g.insert_directed(x1, y0).unwrap();
    g
}

/// `x_{t-1} → y_t`, `x_{t-2} → y_t` (multi-step DGP).
fn lag12_dag() -> TemporalDag {
    let mut g = lag1_dag();
    let x2 = ensure_lagged(&mut g, VariableId::from_raw(0), Lag::from_raw(2)).unwrap();
    let y0 = ensure_lagged(&mut g, VariableId::from_raw(1), Lag::CONTEMPORANEOUS).unwrap();
    g.insert_directed(x2, y0).unwrap();
    g
}

fn pulse() -> TemporalEffectQuery {
    TemporalEffectQuery::pulse(VariableId::from_raw(0), VariableId::from_raw(1), 1.0)
        .with_policy(TemporalPolicy::pulse(-1))
        .with_horizon_steps(1)
}

fn single_sustained() -> TemporalEffectQuery {
    TemporalEffectQuery::sustained(VariableId::from_raw(0), VariableId::from_raw(1), -1, 1.0)
        .with_policy(TemporalPolicy::sustained(-1, -1))
        .with_horizon_steps(1)
}

fn multi_sustained() -> TemporalEffectQuery {
    TemporalEffectQuery::sustained(VariableId::from_raw(0), VariableId::from_raw(1), -2, 1.0)
        .with_policy(TemporalPolicy::sustained(-2, -1))
        .with_horizon_steps(1)
}

fn bayes() -> InferenceMode {
    InferenceMode::Bayesian(BayesianConfig::conjugate().n_draws(DRAWS).prior_scale(10.0))
}

/// Run the study and keep it beside its result, so a coverage tally can bind
/// the execution to the construction the runtime reported.
fn run(
    data: TimeSeriesData,
    graph: impl Into<antecedent::AcceptedGraph>,
    query: TemporalEffectQuery,
    prior: Option<ClassPrior>,
    seed: u64,
) -> (Study, StudyResult) {
    let mut builder = Study::series(data)
        .graph(graph.into())
        .query(CausalQuery::TemporalEffect(query))
        .inference(bayes());
    if let Some(prior) = prior {
        builder = builder.class_prior(prior);
    }
    let study = builder.refute(RefuteSuite::None).bootstrap_replicates(0).build().unwrap();
    let result = study.run(&ExecutionContext::for_tests(seed)).unwrap();
    (study, result)
}

fn credible_interval_at(result: &StudyResult, level: f64) -> Option<(f64, f64)> {
    let post = result.posterior.as_ref()?;
    let draws = post.draws.column(post.effect_column()?).ok()?;
    quantile_interval(draws, level)
}

fn credible_interval(result: &StudyResult) -> Option<(f64, f64)> {
    credible_interval_at(result, LEVEL)
}

#[derive(Clone, Copy, Debug)]
enum Cell {
    Pulse,
    SingleSustained,
    MultiSustained,
}

impl Cell {
    fn query(self) -> TemporalEffectQuery {
        match self {
            Self::Pulse => pulse(),
            Self::SingleSustained => single_sustained(),
            Self::MultiSustained => multi_sustained(),
        }
    }

    const fn beta2(self) -> f64 {
        match self {
            Self::MultiSustained => BETA2,
            Self::Pulse | Self::SingleSustained => 0.0,
        }
    }

    /// True causal contrast of a unit (sustained) treatment change.
    const fn truth(self) -> f64 {
        BETA1 + self.beta2()
    }

    fn graph(self) -> TemporalDag {
        match self {
            Self::MultiSustained => lag12_dag(),
            Self::Pulse | Self::SingleSustained => lag1_dag(),
        }
    }
}

/// Gated at 90%; the runtime's reported 95% credible interval is scored on the
/// same replicates and recorded. `measured` names a grid point as a boundary.
fn coverage(test: &'static str, cell: Cell, regime: Regime, measured: [Option<f64>; 3]) {
    let regime = regime.at_grid();
    let key = RecordKey { test, dgp: "series_xy", interval: "posterior_quantile" };
    let mut tally = CoverageTally::for_record(key, LEVEL);
    let mut reported = CoverageTally::for_record(key, REPORTED_LEVEL).unasserted();
    let runs = map_replicates(n_sim(), |rep| {
        let data = series_xy(regime, rep, cell.beta2());
        run(data, cell.graph(), cell.query(), None, 7 + rep)
    });
    for (study, result) in &runs {
        bind_all(&mut [&mut tally, &mut reported], study, result);
        tally.record(credible_interval(result), cell.truth());
        reported.record(credible_interval_at(result, REPORTED_LEVEL), cell.truth());
    }
    tally.assert_boundary_at(measured);
    reported.emit();
}

macro_rules! dag_coverage {
    ($($test:ident => ($cell:expr, $regime:expr $(, $measured:expr)?);)*) => {$(
        #[test]
        #[ignore = "calibration: run via scripts/gate_calibration.sh"]
        fn $test() {
            coverage(
                stringify!($test),
                $cell,
                $regime,
                dag_coverage!(@measured $($measured)?),
            );
        }
    )*};
    (@measured $measured:expr) => { $measured };
    (@measured) => { [None, None, None] };
}

dag_coverage! {
    bayesian_temporal_pulse_iid_nominal_90_coverage => (Cell::Pulse, Regime::IID);
    bayesian_temporal_pulse_ar1_rho05_n160_nominal_90_coverage =>
        (Cell::Pulse, Regime::RHO05_N160);
    bayesian_temporal_pulse_ar1_rho09_n400_nominal_90_coverage =>
        (Cell::Pulse, Regime::RHO09_N400);
    bayesian_temporal_pulse_ar1_rho05_n60_nominal_90_coverage =>
        (Cell::Pulse, Regime::RHO05_N60, [Some(0.884), None, None]);
    bayesian_temporal_sustained_single_iid_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::IID);
    bayesian_temporal_sustained_single_ar1_rho05_n160_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::RHO05_N160);
    bayesian_temporal_sustained_single_ar1_rho09_n400_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::RHO09_N400);
    bayesian_temporal_sustained_single_ar1_rho05_n60_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::RHO05_N60, [Some(0.884), None, None]);
    bayesian_temporal_sustained_multi_iid_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::IID);
    bayesian_temporal_sustained_multi_ar1_rho05_n160_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::RHO05_N160);
    bayesian_temporal_sustained_multi_ar1_rho09_n400_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::RHO09_N400);
    bayesian_temporal_sustained_multi_ar1_rho05_n60_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::RHO05_N60, [Some(0.883), None, None]);
    // AR(2)(0.3, 0.5) treatment and residual: the REML autoregressive factor with the
    // residual-scale term brings coverage into the band down to n = 60 (the
    // kernel-and-AR(1) factor gave 0.81 at n = 60 and 0.87 at n = 160).
    bayesian_temporal_pulse_ar2_n60_nominal_90_coverage =>
        (Cell::Pulse, Regime::AR2_N60, [Some(0.860), None, None]);
    bayesian_temporal_pulse_ar2_n100_nominal_90_coverage => (Cell::Pulse, Regime::AR2_N100);
    bayesian_temporal_pulse_ar2_n160_nominal_90_coverage =>
        (Cell::Pulse, Regime::AR2_N160, [Some(0.868), None, None]);
    bayesian_temporal_pulse_ar2_n400_nominal_90_coverage => (Cell::Pulse, Regime::AR2_N400);
    bayesian_temporal_sustained_single_ar2_n60_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::AR2_N60, [Some(0.860), None, None]);
    bayesian_temporal_sustained_single_ar2_n100_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::AR2_N100);
    bayesian_temporal_sustained_single_ar2_n160_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::AR2_N160, [Some(0.868), None, None]);
    bayesian_temporal_sustained_single_ar2_n400_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::AR2_N400);
    bayesian_temporal_sustained_multi_ar2_n60_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::AR2_N60, [Some(0.862), None, None]);
    bayesian_temporal_sustained_multi_ar2_n100_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::AR2_N100);
    bayesian_temporal_sustained_multi_ar2_n160_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::AR2_N160);
    bayesian_temporal_sustained_multi_ar2_n400_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::AR2_N400, [None, None, Some(0.883)]);
    // ARMA(1,1) and MA(2) robustness designs: outside the AR(q) family the factor fits.
    bayesian_temporal_pulse_arma11_n60_nominal_90_coverage => (Cell::Pulse, Regime::ARMA11_N60);
    bayesian_temporal_pulse_arma11_n100_nominal_90_coverage =>
        (Cell::Pulse, Regime::ARMA11_N100);
    bayesian_temporal_pulse_arma11_n160_nominal_90_coverage =>
        (Cell::Pulse, Regime::ARMA11_N160);
    bayesian_temporal_pulse_arma11_n400_nominal_90_coverage =>
        (Cell::Pulse, Regime::ARMA11_N400);
    bayesian_temporal_sustained_single_arma11_n60_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::ARMA11_N60);
    bayesian_temporal_sustained_single_arma11_n400_nominal_90_coverage =>
        (Cell::SingleSustained, Regime::ARMA11_N400);
    bayesian_temporal_sustained_multi_arma11_n60_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::ARMA11_N60);
    bayesian_temporal_sustained_multi_arma11_n100_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::ARMA11_N100);
    bayesian_temporal_sustained_multi_arma11_n160_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::ARMA11_N160, [None, None, Some(0.878)]);
    bayesian_temporal_sustained_multi_arma11_n400_nominal_90_coverage =>
        (Cell::MultiSustained, Regime::ARMA11_N400);
    bayesian_temporal_pulse_ma2_n60_nominal_90_coverage =>
        (Cell::Pulse, Regime::MA2_N60, [Some(0.876), None, None]);
    bayesian_temporal_pulse_ma2_n160_nominal_90_coverage => (Cell::Pulse, Regime::MA2_N160);
}

/// Treatment → mediator path `a` of the mediation DGP.
const MED_A: f64 = 0.6;
/// Mediator → outcome path `b`.
const MED_B: f64 = 0.5;
/// Direct treatment → outcome path `c'`.
const MED_C: f64 = 0.4;

/// `m_t = a t_{t-1} + u_t`, `y_t = c' t_{t-1} + b m_t + e_t` with `t`, `u` and `e`
/// independent draws of the regime's noise family (the treatment at
/// [`IID_TREATMENT_RHO`] when the innovations are iid). The mediator's persistence
/// makes the outcome mechanism's `b` score inherit the residual autocorrelation.
/// Columns `t` (0), `m` (1), `y` (2).
fn series_mediation(regime: Regime, rep: u64) -> TimeSeriesData {
    let t = regime.treatment(1.0, regime.stream(rep, 0));
    let u = regime.residual(0.5, regime.stream(rep, 1));
    let e = regime.residual(0.5, regime.stream(rep, 2));
    let mut m = vec![0.0; regime.n];
    let mut y = vec![0.0; regime.n];
    for i in 1..regime.n {
        m[i] = MED_A * t[i - 1] + u[i];
        y[i] = MED_C * t[i - 1] + MED_B * m[i] + e[i];
    }
    TimeSeriesData::from_f64_columns(
        [("t", t.as_slice()), ("m", m.as_slice()), ("y", y.as_slice())],
        1,
    )
    .unwrap()
}

/// `t@1 → m`, `t@1 → y`, `m → y`.
fn mediation_dag() -> TemporalDag {
    let mut g = TemporalDag::empty();
    let t1 = ensure_lagged(&mut g, VariableId::from_raw(0), Lag::from_raw(1)).unwrap();
    let m0 = ensure_lagged(&mut g, VariableId::from_raw(1), Lag::CONTEMPORANEOUS).unwrap();
    let y0 = ensure_lagged(&mut g, VariableId::from_raw(2), Lag::CONTEMPORANEOUS).unwrap();
    g.insert_directed(t1, m0).unwrap();
    g.insert_directed(t1, y0).unwrap();
    g.insert_directed(m0, y0).unwrap();
    g
}

fn run_mediation(data: TimeSeriesData, contrast: MediationContrast, seed: u64) -> StudyResult {
    run_mediation_study(data, contrast, seed).1
}

fn run_mediation_study(
    data: TimeSeriesData,
    contrast: MediationContrast,
    seed: u64,
) -> (Study, StudyResult) {
    let study = Study::series(data)
        .graph(mediation_dag())
        .query(CausalQuery::Mediation(
            MediationQuery::binary(
                VariableId::from_raw(0),
                VariableId::from_raw(2),
                [VariableId::from_raw(1)],
                contrast,
            )
            .with_horizons(vec![1])
            .unwrap(),
        ))
        .inference(bayes())
        .refute(RefuteSuite::None)
        .bootstrap_replicates(0)
        .build()
        .unwrap();
    let result = study.run(&ExecutionContext::for_tests(seed)).unwrap();
    (study, result)
}

/// Total, Direct and Mediated 90% equal-tail coverage of the composed Bayesian
/// temporal mediation posterior (one horizon; columns 1–3 of the posterior).
///
/// The query's contrast is Mediated, so the reported posterior interval (the
/// effect column) is the Mediated column: that tally backs a record, with the
/// reported 95% interval scored on the same replicates. Total and Direct are
/// decomposition columns the facade does not report as an interval: no record.
fn mediation_coverage(test: &'static str, regime: Regime, measured: [[Option<f64>; 3]; 3]) {
    let regime = regime.at_grid();
    let targets =
        [("Total", 1, MED_C + MED_A * MED_B), ("Direct", 2, MED_C), ("Mediated", 3, MED_A * MED_B)];
    let key = RecordKey { test, dgp: "series_mediation", interval: "posterior_quantile" };
    let mut tallies: Vec<CoverageTally> = targets
        .iter()
        .map(|(name, _, _)| {
            if *name == "Mediated" {
                CoverageTally::for_record(key, LEVEL).labelled("mediated")
            } else {
                CoverageTally::new(
                    format!("Bayesian TemporalDag mediation {name} {}", regime.label()),
                    LEVEL,
                )
            }
        })
        .collect();
    let mut reported =
        CoverageTally::for_record(key, REPORTED_LEVEL).labelled("mediated").unasserted();
    let runs = map_replicates(n_sim(), |rep| {
        run_mediation_study(series_mediation(regime, rep), MediationContrast::Mediated, 13 + rep)
    });
    for (study, result) in &runs {
        let post = result.posterior.as_ref().expect("single-horizon mediation posterior");
        for ((name, column, truth), tally) in targets.iter().zip(&mut tallies) {
            let draws = post.draws.column(*column).expect("decomposition draws");
            if *name == "Mediated" {
                bind_all(&mut [&mut *tally, &mut reported], study, result);
                reported.record(quantile_interval(draws, REPORTED_LEVEL), *truth);
            }
            tally.record(quantile_interval(draws, LEVEL), *truth);
        }
    }
    // Print every contrast's calibration line before failing on any of them.
    let failures: Vec<String> = tallies
        .iter()
        .zip(measured)
        .filter_map(|(tally, measured)| {
            std::panic::catch_unwind(|| tally.assert_boundary_at(measured)).err().map(|e| {
                e.downcast_ref::<String>().cloned().unwrap_or_else(|| "coverage failure".into())
            })
        })
        .collect();
    reported.emit();
    assert!(failures.is_empty(), "{}", failures.join("; "));
}

macro_rules! mediation_coverage {
    ($($test:ident => ($regime:expr $(, $measured:expr)?);)*) => {$(
        #[test]
        #[ignore = "calibration: run via scripts/gate_calibration.sh"]
        fn $test() {
            mediation_coverage(
                stringify!($test),
                $regime,
                mediation_coverage!(@measured $($measured)?),
            );
        }
    )*};
    (@measured $measured:expr) => { $measured };
    (@measured) => { [[None, None, None]; 3] };
}

// The Total / Direct / Mediated contrasts of this conjugate-Gaussian
// (prior_scale=10) posterior run consistently a few points warm at 90%
// across every AR/ARMA regime and sample-size grid point measured below
// (0.90-0.94, never under nominal): a stable, conservative-direction
// property of the shared posterior construction, not a per-design defect.
// Values are each cell's own 2000-replicate recheck measurement.
mediation_coverage! {
    bayesian_temporal_mediation_iid_nominal_90_coverage =>
        (Regime::IID, [[None, None, None], [None, None, Some(0.883)], [None, None, None]]);
    bayesian_temporal_mediation_ar1_rho05_n160_nominal_90_coverage =>
        (Regime::RHO05_N160, [[None, None, None], [None, Some(0.915), None], [None, None, None]]);
    bayesian_temporal_mediation_ar1_rho09_n400_nominal_90_coverage => (
        Regime::RHO09_N400,
        [
            [Some(0.928), Some(0.918), None],
            [Some(0.928), Some(0.914), None],
            [Some(0.921), None, None],
        ]
    );
    bayesian_temporal_mediation_ar2_n60_nominal_90_coverage => (
        Regime::AR2_N60,
        [
            [None, Some(0.923), Some(0.929)],
            [None, Some(0.922), Some(0.936)],
            [None, Some(0.931), Some(0.933)],
        ]
    );
    bayesian_temporal_mediation_ar2_n100_nominal_90_coverage => (
        Regime::AR2_N100,
        [
            [Some(0.922), Some(0.931), Some(0.915)],
            [Some(0.914), Some(0.938), Some(0.926)],
            [Some(0.939), Some(0.927), Some(0.921)],
        ]
    );
    bayesian_temporal_mediation_ar2_n160_nominal_90_coverage => (
        Regime::AR2_N160,
        [
            [Some(0.924), Some(0.924), None],
            [Some(0.920), Some(0.930), Some(0.930)],
            [Some(0.927), Some(0.941), Some(0.914)],
        ]
    );
    bayesian_temporal_mediation_ar2_n400_nominal_90_coverage => (
        Regime::AR2_N400,
        [[Some(0.923), None, None], [Some(0.921), None, None], [Some(0.924), None, None]]
    );
    bayesian_temporal_mediation_arma11_n60_nominal_90_coverage => (
        Regime::ARMA11_N60,
        [
            [Some(0.935), Some(0.920), None],
            [Some(0.924), Some(0.916), Some(0.915)],
            [Some(0.931), None, None],
        ]
    );
    bayesian_temporal_mediation_arma11_n160_nominal_90_coverage => (Regime::ARMA11_N160);
    bayesian_temporal_mediation_arma11_n400_nominal_90_coverage => (Regime::ARMA11_N400);
}

/// Both mediation mechanisms are tempered for serial dependence, and the
/// composed posterior records it.
#[test]
fn bayesian_temporal_mediation_tempers_both_mechanisms() {
    let result =
        run_mediation(series_mediation(Regime::RHO09_N400, 0), MediationContrast::Total, 3);
    let post = result.posterior.as_ref().unwrap();
    let kappas: Vec<f64> = post
        .diagnostics
        .notes
        .iter()
        .filter_map(|note| {
            antecedent_estimate::tempering_kappa_from_notes(std::slice::from_ref(note))
        })
        .collect();
    assert_eq!(kappas.len(), 2, "one tempering note per mechanism: {:?}", post.diagnostics.notes);
    assert!(kappas.iter().all(|k| *k > 1.5), "rho 0.9 must temper both mechanisms: {kappas:?}");
    assert!(
        post.diagnostics
            .notes
            .iter()
            .all(|note| !note.contains("scope=") || note.contains("scope=mediation_paths")),
        "{:?}",
        post.diagnostics.notes
    );
    let correction = result
        .diagnostics
        .iter()
        .find(|d| d.code.as_ref() == "estimate.bayesian.temporal.dependence_correction")
        .expect("dependence correction diagnostic");
    let listed = correction.message.split("kappa = [").nth(1).and_then(|t| t.split(']').next());
    assert_eq!(listed.map(|list| list.split(", ").count()), Some(2), "{}", correction.message);
    let product = post
        .assumptions
        .entries
        .iter()
        .find_map(|a| match &a.assumption {
            antecedent_core::Assumption::ParametricRestriction(p)
                if p.id.as_ref() == "temporal.mediation.gaussian_product" =>
            {
                Some(p.description.clone())
            }
            _ => None,
        })
        .expect("gaussian product assumption");
    assert!(product.contains("tempered"), "{product}");
}

/// `conformance/bayesian/release_12_moments`: the tempered mediation posteriors
/// match the independent NIG reference (moments and each mechanism's `κ̂`).
#[test]
fn release_12_mediation_moments_and_tempering_match_the_reference() {
    let fixture: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../conformance/bayesian/release_12_moments/expected.json"
        ))
        .unwrap(),
    )
    .unwrap();
    let column = |name: &str| -> Vec<f64> {
        fixture["data"][name].as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect()
    };
    let lagged = |g: &mut TemporalDag, id: u32, lag: u32| {
        ensure_lagged(g, VariableId::from_raw(id), Lag::from_raw(lag)).unwrap()
    };
    for family in ["mediation", "confounded_mediation"] {
        // Columns t (0), m (1), y (2), plus z (3) in the confounded design.
        let (data, graph) = if family == "mediation" {
            let data = TimeSeriesData::from_f64_columns(
                [("t", column("t").as_slice()), ("m", &column("m")), ("y", &column("o"))],
                1,
            )
            .unwrap();
            let mut g = TemporalDag::empty();
            let (t1, m0, y0) = (lagged(&mut g, 0, 1), lagged(&mut g, 1, 0), lagged(&mut g, 2, 0));
            for (a, b) in [(t1, m0), (t1, y0), (m0, y0)] {
                g.insert_directed(a, b).unwrap();
            }
            (data, g)
        } else {
            let data = TimeSeriesData::from_f64_columns(
                [
                    ("t", column("tc").as_slice()),
                    ("m", &column("mc")),
                    ("y", &column("oc")),
                    ("z", &column("z")),
                ],
                1,
            )
            .unwrap();
            let mut g = TemporalDag::empty();
            let (t0, t1) = (lagged(&mut g, 0, 0), lagged(&mut g, 0, 1));
            let (m0, y0) = (lagged(&mut g, 1, 0), lagged(&mut g, 2, 0));
            let (z0, z1) = (lagged(&mut g, 3, 0), lagged(&mut g, 3, 1));
            for (a, b) in [(z0, t0), (z1, m0), (z1, y0), (t1, m0), (t1, y0), (m0, y0)] {
                g.insert_directed(a, b).unwrap();
            }
            (data, g)
        };
        for scale in [0.1, 10.0] {
            let result = Study::series(data.clone())
                .graph(graph.clone())
                .query(CausalQuery::Mediation(
                    MediationQuery::binary(
                        VariableId::from_raw(0),
                        VariableId::from_raw(2),
                        [VariableId::from_raw(1)],
                        MediationContrast::Mediated,
                    )
                    .with_horizons(vec![1])
                    .unwrap(),
                ))
                .inference(InferenceMode::Bayesian(
                    BayesianConfig::conjugate().n_draws(8192).prior_scale(scale),
                ))
                .refute(RefuteSuite::None)
                .bootstrap_replicates(0)
                .build()
                .unwrap()
                .run(&ExecutionContext::for_tests(1201))
                .unwrap();
            let post = result.posterior.as_ref().unwrap();
            let expected = &fixture["posterior"][format!("{scale:.1}")][family];
            let (mean, var) = (expected[0].as_f64().unwrap(), expected[1].as_f64().unwrap());
            let sd = post.summaries.sd[0];
            assert!(
                (post.summaries.mean[0] - mean).abs() < 0.08 * var.sqrt(),
                "{family} scale {scale}: mean {} vs {mean}",
                post.summaries.mean[0]
            );
            assert!(
                (sd * sd / var - 1.0).abs() < 0.06,
                "{family} scale {scale}: variance {} vs {var}",
                sd * sd
            );
            let mut reported: Vec<f64> = post
                .diagnostics
                .notes
                .iter()
                .filter_map(|note| {
                    antecedent_estimate::tempering_kappa_from_notes(std::slice::from_ref(note))
                })
                .collect();
            let mut pinned: Vec<f64> = fixture["tempering"][family]
                .as_array()
                .unwrap()
                .iter()
                .map(|f| f["kappa"].as_f64().unwrap())
                .collect();
            reported.sort_by(f64::total_cmp);
            pinned.sort_by(f64::total_cmp);
            assert_eq!(reported.len(), pinned.len(), "{family}: {reported:?} vs {pinned:?}");
            for (r, p) in reported.iter().zip(&pinned) {
                assert!((r - p).abs() < 1e-5, "{family} kappa {r} vs pinned {p}");
            }
        }
    }
}

/// `conformance/bayesian/release_12_moments` (`dependent_pulse`): on an AR(2)(0.3, 0.5)
/// treatment and residual the Pulse posterior matches the independently tempered
/// NIG reference, and the reported `κ̂` (REML order 2, residual-scale factor and
/// delta-method spread all active) matches the numpy re-derivation.
#[test]
fn release_12_dependent_pulse_moments_and_tempering_match_the_reference() {
    let fixture: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../conformance/bayesian/release_12_moments/expected.json"
        ))
        .unwrap(),
    )
    .unwrap();
    let column = |name: &str| -> Vec<f64> {
        fixture["data"][name].as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect()
    };
    let data = TimeSeriesData::from_f64_columns(
        [("x", column("td").as_slice()), ("y", column("yd").as_slice())],
        1,
    )
    .unwrap();
    let pinned = &fixture["tempering"]["dependent_pulse"][0];
    assert!(pinned["residual_ar_order"].as_u64() == Some(2), "{pinned}");
    assert!(pinned["kappa_log_sd"].as_f64().unwrap() > 0.1, "{pinned}");
    for scale in [0.1, 10.0] {
        let result = Study::series(data.clone())
            .graph(lag1_dag())
            .query(CausalQuery::TemporalEffect(pulse()))
            .inference(InferenceMode::Bayesian(
                BayesianConfig::conjugate().n_draws(8192).prior_scale(scale),
            ))
            .refute(RefuteSuite::None)
            .bootstrap_replicates(0)
            .build()
            .unwrap()
            .run(&ExecutionContext::for_tests(1202))
            .unwrap();
        let post = result.posterior.as_ref().unwrap();
        let expected = &fixture["posterior"][format!("{scale:.1}")]["dependent_pulse"];
        let (mean, var) = (expected[0].as_f64().unwrap(), expected[1].as_f64().unwrap());
        let draws = post.draws.column(post.effect_column().unwrap()).unwrap();
        let n = draws.len() as f64;
        let draw_mean = draws.iter().sum::<f64>() / n;
        let draw_var = draws.iter().map(|d| (d - draw_mean).powi(2)).sum::<f64>() / (n - 1.0);
        assert!(
            (draw_mean - mean).abs() < 0.08 * var.sqrt(),
            "scale {scale}: mean {draw_mean} vs {mean}"
        );
        assert!((draw_var / var - 1.0).abs() < 0.06, "scale {scale}: variance {draw_var} vs {var}");
        let kappa = antecedent_estimate::tempering_kappa_from_notes(&post.diagnostics.notes)
            .expect("tempering note");
        let pinned_kappa = pinned["kappa"].as_f64().unwrap();
        assert!((kappa - pinned_kappa).abs() < 1e-5, "kappa {kappa} vs pinned {pinned_kappa}");
        assert!(kappa > 4.0, "the AR(2) design must be tempered well beyond the AR(1) value");
    }
}

/// `t_t = 0.4 z_t + 0.5 u_t`, `y_t = 0.8 t_{t-1} + e_t`; `z`, `u`, `e` independent AR(1).
///
/// `z_{t-1} — t_{t-1}` is undirected in the class. Both completions target the
/// same effect (z has no path to y), so the class-prior mixture functional is
/// `0.8`; the completions differ in their adjustment set and posterior width.
fn series_tyz(regime: Regime, rep: u64) -> TimeSeriesData {
    let z = regime.residual(1.0, regime.stream(rep, 0));
    let u = regime.residual(1.0, regime.stream(rep, 1));
    let e = regime.residual(0.35, regime.stream(rep, 2));
    let t: Vec<f64> = z.iter().zip(&u).map(|(z, u)| 0.4 * z + 0.5 * u).collect();
    let mut y = vec![0.0; regime.n];
    for i in 1..regime.n {
        y[i] = BETA1 * t[i - 1] + e[i];
    }
    TimeSeriesData::from_f64_columns(
        [("t", t.as_slice()), ("y", y.as_slice()), ("z", z.as_slice())],
        1,
    )
    .unwrap()
}

fn tyz_cpdag() -> TemporalCpdag {
    let mut g = TemporalCpdag::empty();
    let t1 = g.add_lagged(VariableId::from_raw(0), Lag::from_raw(1)).unwrap();
    let y0 = g.add_lagged(VariableId::from_raw(1), Lag::CONTEMPORANEOUS).unwrap();
    let z1 = g.add_lagged(VariableId::from_raw(2), Lag::from_raw(1)).unwrap();
    g.insert_directed(z1, y0).unwrap();
    g.insert_directed(t1, y0).unwrap();
    g.insert_undirected(z1, t1).unwrap();
    g
}

#[test]
#[ignore = "calibration: run via scripts/gate_calibration.sh"]
fn bayesian_temporal_cpdag_class_prior_ar1_rho05_n160_nominal_90_coverage() {
    let regime = Regime::RHO05_N160.at_grid();
    let prior = ClassPrior::from_ordered([0.5, 0.5]).unwrap();
    let key = RecordKey {
        test: "bayesian_temporal_cpdag_class_prior_ar1_rho05_n160_nominal_90_coverage",
        dgp: "series_tyz",
        interval: "posterior_quantile",
    };
    let mut tally = CoverageTally::for_record(key, LEVEL);
    let mut reported = CoverageTally::for_record(key, REPORTED_LEVEL).unasserted();
    let runs = map_replicates(n_sim(), |rep| {
        run(series_tyz(regime, rep), tyz_cpdag(), pulse(), Some(prior.clone()), 11 + rep)
    });
    for (study, result) in &runs {
        bind_all(&mut [&mut tally, &mut reported], study, result);
        tally.record(credible_interval(result), BETA1);
        reported.record(credible_interval_at(result, REPORTED_LEVEL), BETA1);
    }
    tally.assert();
    reported.emit();
}

/// The composed Bayesian refitter resamples lag-aligned rows for
/// `bootstrap.ci_coverage` instead of rebuilding lags on a block-resampled raw
/// series (which pairs outcomes with regressors from unrelated blocks).
#[test]
fn bayesian_multi_step_bootstrap_refuter_resamples_aligned_rows() {
    let result = Study::series(series_xy(Regime::RHO05_N160, 0, BETA2))
        .graph(lag12_dag())
        .query(CausalQuery::TemporalEffect(multi_sustained()))
        .inference(bayes())
        .refute(RefuteSuite::Full)
        .bootstrap_replicates(0)
        .build()
        .unwrap()
        .run(&ExecutionContext::for_tests(3))
        .unwrap();
    let report = result
        .refutations
        .iter()
        .find(|r| r.refuter.as_ref() == "bootstrap.ci_coverage")
        .expect("the composed Bayesian contrast runs bootstrap.ci_coverage");
    assert!(report.replicates > 0 && report.refuted_ate.is_finite(), "{report:?}");
    assert!(
        !result.diagnostics.iter().any(|d| d.code.as_ref() == "refute.validator.not_applicable"
            && d.message.contains("bootstrap")),
        "bootstrap.ci_coverage must not be skipped"
    );
    // The replicate least-squares contrast stands in for the tempered posterior mean.
    let stand_in = result
        .diagnostics
        .iter()
        .find(|d| d.code.as_ref() == "refute.bootstrap.ci_coverage.least_squares_stand_in")
        .expect("the Bayesian check discloses its least-squares stand-in");
    assert!(stand_in.message.contains("tempered by 1/kappa"), "{}", stand_in.message);
}
