# Named allowlist: cells that are neither licensed nor closed but do genuinely
# run end-to-end today. Each row is proof-carrying — `reason` states why it runs
# and why it is not licensed instead (no staged handle / re-identifies per click /
# no cell-shaped evidence fixture), and `parent` names the licensed or
# keep-running family it rides. An allowed rule must not match any licensed, n/a,
# or closed cell (parity/gate_support_matrix.sh enforces the partition).
#
# Empty as of 0.9.0: every previously allowlisted running cell is now licensed
# (Pag/Admg ATE, graph-posterior Bayesian ATE, Pulse DBN posterior none).
# See adr/0020, 2026-08-19 amendment.
